const PRODUCTS = [
  {
    id: "barricade-65wg",
    fullName: "Barricade 65WG Herbicide, Syngenta",
    brand: "Syngenta",
    category: "herbicide",
    type: ["pre-emergent"],
    formulation: "granule",
    activeIngredients: [
      "Prodiamine 65%"
    ],
    genericAlternatives: [
        {
        fullName: "Prodiamine 65 WDG Herbicide, Quali-Pro", // Quali-Pro is a brand of Control Solutions, Inc.
        activeIngredient: "Prodiamine 65%",
        note: "Same active ingredient and concentration. Generic alternative. Typically lowest cost option."
        },
        {
        fullName: "Resolute 65 WG Herbicide, Syngenta",
        activeIngredient: "Prodiamine 65%",
        note: "Same product as Barricade 65WG under a different Syngenta brand name"
        },
        {
        fullName: "Prodiamine 65 WG Herbicide, Alligare",
        activeIngredient: "Prodiamine 65%",
        note: "Same active ingredient and concentration. Generic alternative."
        }
    ],
    mixUnit: "oz",
    perUnit: 1000,
    rateMin: 0.185,                  // fall/spring split app (low end)
    rateMax: 0.83,                  // single app (high end)
    rateDefault: 0.36,
    turfRates: [
        {
            turfGroup: [
            "Bahiagrass", "Bermudagrass", "Centipedegrass", "Kikuyugrass",
            "Seashore Paspalum", "St. Augustinegrass", "Tall Fescue", "Zoysiagrass"
            ],
            rateMin: 0.36,
            rateMax: 0.83
        },
        {
            turfGroup: ["Buffalograss", "Kentucky Bluegrass", "Perennial Ryegrass"],
            rateMin: 0.185,
            rateMax: 0.55
        },
        {
            turfGroup: ["Fine Fescue"],
            rateMin: 0.185,
            rateMax: 0.42
        },
        {
            turfGroup: ["Creeping Bentgrass"],
            rateMin: 0.185,
            rateMax: 0.37,
            notes: "Must be mowed at 0.5 inches or more in height"
        }
    ],
    waterPerUnit: 0.5,
    turfTypes: [
        "Bahiagrass",
        "Bermudagrass",
        "Buffalograss",
        "Centipedegrass",
        "Creeping Bentgrass",
        "Fine Fescue",
        "Kentucky Bluegrass",
        "Kikuyugrass",
        "Perennial Ryegrass",
        "Seashore Paspalum",
        "St. Augustinegrass",
        "Tall Fescue",
        "Zoysiagrass"
    ],
    notSafeTurf: [
        "Dichondra (do not apply where desirable)",
        "Colonial Bentgrass (do not apply where desirable)",
        "Velvet Bentgrass (do not apply where desirable)",
        "Newly seeded areas (wait 60 days after germination)",
        "Newly set sod (wait until rooted and edges filled in)"
    ],
    targetWeeds: [
      { label: "Barnyardgrass", ids: ["barnyardgrass"] },
      { label: "Bluegrass, Annual (Poa annua)", ids: ["annual-bluegrass"] },
      { label: "Carpetweed", ids: ["carpetweed"] },
      { label: "Chickweed, Common", ids: ["chickweed"] },
      { label: "Chickweed, Mouseear (from seed)", ids: ["mouseear-chickweed"] },
      { label: "Crabgrass (Large, Smooth)", ids: ["crabgrass-large", "crabgrass-smooth"] },
      { label: "Crowfootgrass", ids: ["crowfootgrass"] },
      { label: "Cupgrass, Woolly", ids: ["woolly-cupgrass"] },
      { label: "Foxtails, Annual", ids: ["foxtail"] },
      { label: "Goosegrass", ids: ["goosegrass"] },
      { label: "Henbit", ids: ["henbit"] },
      { label: "Itchgrass", ids: ["itchgrass"] },
      { label: "Johnsongrass (from seed)", ids: ["johnsongrass"] },
      { label: "Junglerice", ids: ["junglerice"] },
      { label: "Knotweed", ids: ["knotweed"] },
      { label: "Kochia", ids: ["kochia"] },
      { label: "Lambsquarter, Common", ids: ["lambsquarters"] },
      { label: "Lovegrass", ids: ["lovegrass"] },
      { label: "Panicum (Texas, Fall, Browntop)", ids: ["texas-panicum", "fall-panicum", "browntop-millet"] },
      { label: "Pigweed", ids: ["pigweed"] },
      { label: "Purslane, Common", ids: ["purslane"] },
      { label: "Pusley, Florida", ids: ["florida-pusley"] },
      { label: "Rescuegrass", ids: ["rescuegrass"] },
      { label: "Shepherd's Purse", ids: ["shepherds-purse"] },
      { label: "Signalgrass, Broadleaf", ids: ["signalgrass-broadleaf"] },
      { label: "Speedwell, Persian", ids: ["speedwell-persian"] },
      { label: "Sprangletop", ids: ["sprangletop"] },
      { label: "Spurge, Prostrate", ids: ["prostrate-spurge"] },
      { label: "Witchgrass", ids: ["witchgrass"] },
      { label: "Woodsorrel, Yellow (from seed)", ids: ["woodsorrel-yellow"] }
    ],
    containerSizes: [
      { label: "5 lb jug", oz: 80 },
    ],
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until dry",
    applicationNotes: [
        "Apply before target weeds germinate — this product will not control weeds that have already emerged",
        "Activate with at least 0.5 inch of rainfall or irrigation within 14 days of application",
        "For spring crabgrass control in cool-season grasses: apply in fall after soil temperature drops below 50°F but before ground freezes",
        "For summer annual weeds: apply in early spring before soil temperature reaches germination threshold for your region",
        "Do not disturb soil after application — cultivation breaks the herbicide barrier and reduces weed control"
    ],
    restrictions: [
        "Do not apply to golf course putting greens",
        "Do not apply where dichondra, colonial bentgrass, or velvet bentgrass are desirable",
        "Do not harvest sod within 90 days of application",
        "Do not apply to stressed turf (drought, low fertility, pest damage)",
        "Do not apply to newly set sod until rooted and edges filled in",
        "Wait 60 days after seeding or until after second mowing (whichever is longer) before applying to overseeded areas"
    ],
    labelUrl: "https://www3.epa.gov/pesticides/chem_search/ppls/000100-00834-20040521.pdf"
  },
  {
    id: "blindside-herbicide",
    fullName: "Blindside Herbicide WDG",
    brand: "Envu (Environmental Science U.S., LLC)",
    category: "herbicide",
    type: "post-emergent",
    formulation: "WDG",
    activeIngredients: [
      "Sulfentrazone 60% (HRAC Group 14)",
      "Metsulfuron-methyl 6% (HRAC Group 2)"
    ],
    genericAlternatives: [],
    mixUnit: "oz",
    perUnit: "1000sqft",
    rateMin: 0.075,
    rateMax: 0.23,
    rateDefault: 0.115,
    turfRates: [
      {
        turfTypes: ["kentucky-bluegrass", "tall-fescue"],
        rateMin: 0.075,
        rateMax: 0.115
      },
      {
        turfTypes: ["bermudagrass", "buffalograss", "centipedegrass", "st-augustinegrass", "zoysiagrass"],
        rateMin: 0.115,
        rateMax: 0.23
      }
    ],
    annualMaxPer1k: 0.23,
    waterPerUnit: 2,
    turfTypes: [
      "bermudagrass",
      "buffalograss",
      "centipedegrass",
      "kentucky-bluegrass",
      "st-augustinegrass",
      "tall-fescue",
      "zoysiagrass"
    ],
    notSafeTurf: [
      "bahiagrass"
    ],
    targetWeeds: [
      { label: "Bittercress", ids: ["hairy-bittercress"] },
      { label: "Barnyardgrass", ids: ["barnyardgrass"] },
      { label: "Black medic", ids: ["black-medic"] },
      { label: "Bluegrass, annual", ids: ["annual-bluegrass"] },
      { label: "Buttercups", ids: ["buttercup"] },
      { label: "Buttonweed, Virginia", ids: ["virginia-buttonweed"] },
      { label: "Carolina geranium", ids: ["geranium-carolina"] },
      { label: "Carpetweed", ids: ["carpetweed"] },
      { label: "Chickweed, common", ids: ["chickweed"] },
      { label: "Chickweed, mousear", ids: ["mouseear-chickweed"] },
      { label: "Cinquefoil", ids: ["cinquefoil"] },
      { label: "Clover", ids: ["clover"] },
      { label: "Crabgrass (Large and Smooth)", ids: ["crabgrass-large", "crabgrass-smooth"] },
      { label: "Creeping Beggarweed", ids: ["beggarweed-creeping"] },
      { label: "Crown Vetch", ids: ["crown-vetch", "vetch-common"] },
      { label: "Cudweed", ids: ["cudweed"] },
      { label: "Dandelion", ids: ["dandelion"] },
      { label: "Dock, Curly", ids: ["dock-curly"] },
      { label: "Dogfennel", ids: ["dogfennel"] },
      { label: "Dollarweed", ids: ["water-pennywort"] },
      { label: "Doveweed", ids: ["doveweed"] },
      { label: "Eclipta", ids: ["eclipta"] },
      { label: "Evening primrose", ids: ["evening-primrose-common"] },
      { label: "Fiddleneck", ids: ["fiddleneck"] },
      { label: "Filaree", ids: ["filaree"] },
      { label: "Foxtail spp.", ids: ["foxtail"] },
      { label: "Groundsel", ids: ["groundsel"] },
      { label: "Goldenrod", ids: ["goldenrod"] },
      { label: "Ground ivy", ids: ["ground-ivy"] },
      { label: "Henbit", ids: ["henbit"] },
      { label: "Japanese Stiltgrass", ids: ["stiltgrass"] },
      { label: "Knotweed, prostrate", ids: ["knotweed"] },
      { label: "Kochia", ids: ["kochia"] },
      { label: "Kyllinga, green", ids: ["green-kyllinga"] },
      { label: "Kyllinga, False green", ids: ["false-green-kyllinga"] },
      { label: "Lambsquarters, common", ids: ["lambsquarters"] },
      { label: "Lawn burweed", ids: ["lawn-burweed"] },
      { label: "Lespedeza, common", ids: ["japanese-clover"] },
      { label: "London Rocket", ids: ["london-rocket"] },
      { label: "Mallow, common", ids: ["malva"] },
      { label: "Miner Lettuce", ids: ["miners-lettuce"] },
      { label: "Morningglory", ids: ["morningglory"] },
      { label: "Mustard, Tansy", ids: ["tansy-mustard"] },
      { label: "Mustard, Tumble", ids: ["jim-hill-mustard"] },
      { label: "Nutsedge, Purple", ids: ["nutsedge-purple"] },
      { label: "Nutsedge, Yellow", ids: ["nutsedge-yellow"] },
      { label: "Parsley piert", ids: ["parsley-piert"] },
      { label: "Pigweed, Redroot", ids: ["pigweed-redroot"] },
      { label: "Pigweed, Smooth", ids: ["pigweed-smooth"] },
      { label: "Pigweed, Tumble", ids: ["pigweed-tumble"] },
      { label: "Pineapple weed", ids: ["pineappleweed"] },
      { label: "Plantain, broadleaf", ids: ["plantain-broadleaf"] },
      { label: "Plantain, buckhorn", ids: ["plantain-buckhorn"] },
      { label: "Prickly Lettuce", ids: ["prickly-lettuce"] },
      { label: "Puncture weed", ids: ["puncturevine"] },
      { label: "Purslane, common", ids: ["purslane"] },
      { label: "Pusley, Florida", ids: ["florida-pusley"] },
      { label: "Sedge, Globe", ids: ["globe-sedge"] },
      { label: "Sedge, annual", ids: ["annual-sedge"] },
      { label: "Sedge, cylindric", ids: ["cylindric-sedge"] },
      { label: "Shepherd's Purse", ids: ["shepherds-purse"] },
      { label: "Smartweed, Pennsylvania", ids: ["smartweed-pennsylvania"] },
      { label: "Sorrel, Red", ids: ["red-sorrel"] },
      { label: "Speedwell", ids: ["speedwell"] },
      { label: "Spurge, (annuals)", ids: ["spurge"] },
      { label: "Spurge, prostrate", ids: ["spreading-spurge"] },
      { label: "Spurge, spotted", ids: ["spotted-spurge"] },
      { label: "Star of Bethlehem", ids: ["star-of-bethlehem"] },
      { label: "Violet, wild", ids: ["violet-common-blue"] },
      { label: "Wild garlic", ids: ["wild-garlic"] },
      { label: "Wild onion", ids: ["wild-onion"] },
      { label: "Woodsorrel, creeping", ids: ["woodsorrel-creeping"] },
      { label: "Woodsorrel, yellow", ids: ["woodsorrel-yellow"] }
    ],
    containerSizes: [],
    EPAtoxicityLevel: "III",
    reentryInterval: 12,
    applicationNotes: [
      "Do not apply to golf course putting greens, collars, or tees.",
      "Do not apply to turfgrass under stress.",
      "Best results when no rainfall or irrigation occurs within 24 hours of application.",
      "If no rainfall or irrigation occurs within 7 days of application, irrigate with at least 0.5 inches of water.",
      "Do not use on coarse sand soils with less than 1% organic matter.",
      "Use of surfactants is not recommended — may cause temporary turf discoloration.",
      "Do not apply or tank-mix with trinexapac-ethyl (e.g., Primo Maxx) within 7 days in either direction to reduce risk of discoloration.",
      "Reseeding, overseeding, or sprigging treated areas within 1 month of application may inhibit establishment of desirable turfgrass.",
      "Cool-season grasses (KBG, tall fescue): use 0.075–0.115 oz/1,000 sq ft. Warm-season grasses: use 0.115–0.23 oz/1,000 sq ft.",
      "Apply at 0.5–4.0 gallons of spray solution per 1,000 sq ft at 20–40 psi. Use higher spray volumes for dense weed populations.",
      "Do not leave spray mixture standing in tank — apply immediately after mixing.",
      "Centipedegrass: discoloration may occur if air temperature is below 70°F at time of application.",
      "Zoysiagrass: application during spring transition may result in discoloration."
    ],
    restrictions: [
      "Do not apply aerially.",
      "Do not apply through any type of irrigation system.",
      "Do not treat pastures, rangeland, or areas grazed or harvested for livestock forage or hay.",
      "Maximum annual sulfentrazone rate: 0.375 lbs ai/acre (= 0.23 oz product/1,000 sq ft) per calendar year.",
      "Do not apply directly to landscape ornamentals or ornamental beds.",
      "Do not allow spray drift to contact landscape ornamentals, shrubs, or trees.",
      "Do not plant shrubs or trees in treated areas for one year after application; bedding plants for two years.",
      "Do not use clippings as mulch or compost around flowers, ornamentals, trees, or in vegetable gardens.",
      "Do not apply when wind speeds exceed 10 mph.",
      "Do not apply during temperature inversions.",
      "Minimum 50-foot setback from wells, sink holes, streams, rivers, and lakes during mixing and loading.",
      "Do not use on turfgrass other than those listed on this label."
    ],
    labelUrl: "https://bynder.envu.com/m/41196881a96d8876/original/Digital_FMC_Golf_Blindside_Label_NA_US_EN.pdf"
  },
  {
    id: "celsius-wg",
    fullName: "Celsius WG Herbicide, Envu",
    brand: "Envu",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "granule",          // "granule" or "liquid"
    activeIngredients: [
        "Thiencarbazone-methyl 8.7%",
        "Iodosulfuron-methyl-sodium 1.9%",
        "Dicamba 57.4%"
    ],
    genericAlternatives: [],
    mixUnit: "oz",                   // unit the label uses for mixing
    perUnit: 1000,                   // per how many sq ft
    rateMin: 0.057,                  // oz per 1000 sq ft
    rateMax: 0.113,                  // oz per 1000 sq ft
    rateDefault: 0.057,
    rateTiers: [
      { label: "Low",    ozPer1k: 0.057 },
      { label: "Medium", ozPer1k: 0.085 },
      { label: "High",   ozPer1k: 0.113 }
    ],
    annualMaxPer1k: 0.17,
    waterPerUnit: 1,   // gal per 1,000 sq ft (zone/spot)
    turfTypes: [
        "Bermudagrass",
        "Centipedegrass",
        "St. Augustinegrass",
        "Zoysiagrass"
    ],
    notSafeTurf: [
        "Bahiagrass",
        "Creeping Bentgrass",
        "Fine Fescue",
        "Kentucky Bluegrass",
        "Perennial Ryegrass",
        "Seashore Paspalum",
        "Tall Fescue"
    ],
    targetWeeds: [
      { label: "American burnweed, Fireweed", ids: ["american-burnweed"], rateRequired: "Medium" },
      { label: "Annual lespedeza", ids: ["japanese-clover"], rateRequired: "High" },
      { label: "Asiatic hawksbeard", ids: ["asiatic-hawksbeard"], rateRequired: "Medium" },
      { label: "Barnyardgrass", ids: ["barnyardgrass"], rateRequired: "Low" },
      { label: "Birdseye pearlwort", ids: ["birdseye-pearlwort"], rateRequired: "High" },
      { label: "Black medic, hop medic", ids: ["black-medic"], rateRequired: "High" },
      { label: "Black nightshade", ids: ["nightshade-black"], rateRequired: "Medium" },
      { label: "Blackseed plantain", ids: ["blackseed-plantain"], rateRequired: "Low" },
      { label: "Bracted plantain", ids: ["bracted-plantain"], rateRequired: "Low" },
      { label: "Broadleaf plantain, common plantain", ids: ["plantain-broadleaf"], rateRequired: "Low" },
      { label: "Broadleaf signalgrass", ids: ["signalgrass-broadleaf"], rateRequired: "Medium" },
      { label: "Browntop millet", ids: ["browntop-millet"], rateRequired: "Medium" },
      { label: "Buckhorn plantain, narrowleaf plantain", ids: ["plantain-buckhorn"], rateRequired: "Low" },
      { label: "California burclover", ids: ["burclover"], rateRequired: "Low" },
      { label: "Canada thistle", ids: ["thistle-canada"], rateRequired: "Medium" },
      { label: "Canada toadflax", ids: ["canada-toadflax"], rateRequired: "Medium" },
      { label: "Carolina dichondra, Dichondra", ids: ["dichondra"], rateRequired: "Medium" },
      { label: "Carolina falsedandelion", ids: ["carolina-falsedandelion"], rateRequired: "Low" },
      { label: "Carolina geranium, wild geranium", ids: ["geranium-carolina"], rateRequired: "Medium" },
      { label: "Carpetgrass", ids: ["carpetgrass-common"], rateRequired: "Medium" },
      { label: "Carpetweed, Indian chickweed", ids: ["carpetweed"], rateRequired: "Low" },
      { label: "Catsear dandelion", ids: ["catsear"], rateRequired: "Low" },
      { label: "Chamberbitter", ids: ["chamberbitter"], rateRequired: "Medium" },
      { label: "Common chickweed", ids: ["chickweed"], rateRequired: "Low" },
      { label: "Common lambsquarter", ids: ["lambsquarters"], rateRequired: "Medium" },
      { label: "Common millet, proso millet", ids: ["proso-millet"], rateRequired: "Low" },
      { label: "Common purslane", ids: ["purslane"], rateRequired: "Medium" },
      { label: "Common ragweed", ids: ["ragweed"], rateRequired: "Low" },
      { label: "Common sunflower", ids: ["common-sunflower"], rateRequired: "Low" },
      { label: "Common vetch", ids: ["vetch-common"], rateRequired: "Low" },
      { label: "Common waterhemp", ids: ["waterhemp"], rateRequired: "Medium" },
      { label: "Corn speedwell", ids: ["speedwell-corn"], rateRequired: "Medium" },
      { label: "Creeping beggarweed", ids: ["beggarweed-creeping"], rateRequired: "Low" },
      { label: "Creeping speedwell", ids: ["speedwell-slender"], rateRequired: "Medium" },
      { label: "Curly dock", ids: ["dock-curly"], rateRequired: "Low" },
      { label: "Cutleaf evening primrose", ids: ["evening-primrose-cutleaf"], rateRequired: "Low" },
      { label: "Dallisgrass", ids: ["dallisgrass"], rateRequired: "High" },
      { label: "Dandelion", ids: ["dandelion"], rateRequired: "Low" },
      { label: "Dogfennel", ids: ["dogfennel"], rateRequired: "Medium" },
      { label: "Dollarweed, Pennywort", ids: ["water-pennywort"], rateRequired: "Medium" },
      { label: "Doveweed", ids: ["doveweed"], rateRequired: "High" },
      { label: "Eastern black nightshade", ids: ["nightshade-eastern-black"], rateRequired: "Low" },
      { label: "Entireleaf morningglory", ids: ["morningglory-ivyleaf"], rateRequired: "Medium" },
      { label: "Facelis, trampweed", ids: ["facelis"], rateRequired: "Medium" },
      { label: "Fall panicum", ids: ["fall-panicum"], rateRequired: "Medium" },
      { label: "Field madder", ids: ["field-madder"], rateRequired: "Low" },
      { label: "Field pepperweed", ids: ["field-pepperweed"], rateRequired: "Medium" },
      { label: "Field sandbur", ids: ["sandbur-field"], rateRequired: "Medium" },
      { label: "Field violet, wild pansy", ids: ["violet-field"], rateRequired: "Low" },
      { label: "Fleabane", ids: ["canada-fleabane", "fleabane-rough"], rateRequired: "Medium" },
      { label: "Florida betony", ids: ["florida-betony"], rateRequired: "Medium" },
      { label: "Florida pusley", ids: ["florida-pusley"], rateRequired: "High" },
      { label: "Giant foxtail", ids: ["foxtail-giant"], rateRequired: "Low" },
      { label: "Giant ragweed", ids: ["giant-ragweed"], rateRequired: "Low" },
      { label: "Gophertail lovegrass", ids: ["lovegrass-gophertail"], rateRequired: "Medium" },
      { label: "Green foxtail", ids: ["foxtail-green"], rateRequired: "Low" },
      { label: "Green kyllinga", ids: ["green-kyllinga"], rateRequired: "Medium" },
      { label: "Ground ivy, Creeping Charlie", ids: ["ground-ivy"], rateRequired: "Low" },
      { label: "Hairy bittercress", ids: ["hairy-bittercress"], rateRequired: "Low" },
      { label: "Heartwing sorrel", ids: ["heartwing-sorrel"], rateRequired: "Medium" },
      { label: "Heath aster", ids: ["aster-white-heath"], rateRequired: "Medium" },
      { label: "Hemp sesbania", ids: ["hemp-sesbania"], rateRequired: "High" },
      { label: "Henbit", ids: ["henbit"], rateRequired: "Low" },
      { label: "Horse purslane", ids: ["horse-purslane"], rateRequired: "Low" },
      { label: "Horseweed, marestail", ids: ["canada-fleabane"], rateRequired: "Medium" },
      { label: "Ivyleaf morningglory", ids: ["morningglory-ivyleaf"], rateRequired: "Medium" },
      { label: "Johnsongrass", ids: ["johnsongrass"], rateRequired: "Low" },
      { label: "Knawel", ids: ["knawel"], rateRequired: "Medium" },
      { label: "Lady's Mantle", ids: ["ladys-mantle"], rateRequired: "Medium" },
      { label: "Large crabgrass", ids: ["crabgrass-large"], rateRequired: "High" },
      { label: "Lawn burweed, spurweed", ids: ["lawn-burweed"], rateRequired: "Low" },
      { label: "Mouse-ear chickweed", ids: ["mouseear-chickweed-sticky"], rateRequired: "Medium" },
      { label: "Oxeye daisy", ids: ["oxeye-daisy"], rateRequired: "Low" },
      { label: "Paleseed plantain", ids: ["paleseed-plantain"], rateRequired: "Medium" },
      { label: "Palmer amaranth", ids: ["palmer-amaranth"], rateRequired: "Low" },
      { label: "Parsley piert", ids: ["parsley-piert-slender"], rateRequired: "Medium" },
      { label: "Pennsylvania smartweed", ids: ["smartweed-pennsylvania"], rateRequired: "Low" },
      { label: "Pitted morningglory", ids: ["morningglory-pitted"], rateRequired: "Low" },
      { label: "Pokeberry", ids: ["pokeweed"], rateRequired: "Medium" },
      { label: "Poorjoe", ids: ["poorjoe"], rateRequired: "Medium" },
      { label: "Prickly sida", ids: ["prickly-sida"], rateRequired: "Medium" },
      { label: "Prostrate knotweed", ids: ["knotweed"], rateRequired: "Medium" },
      { label: "Prostrate spurge", ids: ["spotted-spurge"], rateRequired: "High" },
      { label: "Purple cudweed", ids: ["cudweed"], rateRequired: "High" },
      { label: "Quackgrass", ids: ["quackgrass"], rateRequired: "Low" },
      { label: "Rabbitfoot clover", ids: ["rabbitfoot-clover"], rateRequired: "Low" },
      { label: "Red fescue", ids: ["red-fescue-weed-escape"], rateRequired: "Medium" },
      { label: "Red sorrel", ids: ["red-sorrel"], rateRequired: "Low" },
      { label: "Redroot pigweed", ids: ["pigweed-redroot"], rateRequired: "Low" },
      { label: "Rescuegrass", ids: ["rescuegrass"], rateRequired: "Medium" },
      { label: "Russian thistle", ids: ["russian-thistle"], rateRequired: "Medium" },
      { label: "Ryegrass (clumpy)", ids: ["ryegrass-perennial"], rateRequired: "High" },
      { label: "Shattercane", ids: ["shattercane"], rateRequired: "Medium" },
      { label: "Shepherd's purse", ids: ["shepherds-purse"], rateRequired: "Medium" },
      { label: "Sicklepod", ids: ["sicklepod"], rateRequired: "Medium" },
      { label: "Slender aster", ids: ["slender-aster"], rateRequired: "Medium" },
      { label: "Spiny sowthistle", ids: ["sowthistle-spiny"], rateRequired: "Medium" },
      { label: "Sprawling horseweed", ids: ["sprawling-horseweed"], rateRequired: "Medium" },
      { label: "Stinkgrass", ids: ["stinkgrass"], rateRequired: "Medium" },
      { label: "Switchgrass", ids: ["switchgrass"], rateRequired: "Medium" },
      { label: "Swinecress", ids: ["swinecress"], rateRequired: "Medium" },
      { label: "Tall fescue", ids: ["fescue-weed-escape"], rateRequired: "Medium" },
      { label: "Tansy mustard", ids: ["tansy-mustard"], rateRequired: "Medium" },
      { label: "Texas panicum", ids: ["texas-panicum"], rateRequired: "Medium" },
      { label: "Thin paspalum, bull paspalum", ids: ["thin-paspalum"], rateRequired: "Medium" },
      { label: "Velvetleaf", ids: ["abutilon"], rateRequired: "Medium" },
      { label: "Venus looking-glass", ids: ["venus-looking-glass"], rateRequired: "Medium" },
      { label: "Virginia buttonweed", ids: ["virginia-buttonweed"], rateRequired: "High" },
      { label: "Virginia dwarf dandelion", ids: ["virginia-dwarf-dandelion"], rateRequired: "Medium" },
      { label: "Western ragweed", ids: ["ragweed-western"], rateRequired: "High" },
      { label: "White clover", ids: ["white-clover"], rateRequired: "Medium" },
      { label: "White mustard", ids: ["mustard-white"], rateRequired: "Medium" },
      { label: "White sweet clover", ids: ["sweet-clover-white"], rateRequired: "Medium" },
      { label: "Whiteleaf sage", ids: ["whiteleaf-sage"], rateRequired: "High" },
      { label: "Wild buckwheat", ids: ["wild-buckwheat"], rateRequired: "Medium" },
      { label: "Wild carrot", ids: ["wild-carrot"], rateRequired: "Medium" },
      { label: "Wild lettuce, tall lettuce", ids: ["wild-lettuce-tall"], rateRequired: "Medium" },
      { label: "Wild oat", ids: ["wild-oats"], rateRequired: "Medium" },
      { label: "Wild onion", ids: ["wild-onion"], rateRequired: "Medium" },
      { label: "Yellow foxtail", ids: ["foxtail-yellow"], rateRequired: "Medium" },
      { label: "Yellow rocket", ids: ["yellow-rocket"], rateRequired: "Medium" },
      { label: "Yellow woodsorrel", ids: ["woodsorrel-yellow"], rateRequired: "Medium" }
    ],
    containerSizes: [
      { label: "Single-dose pack", oz: 0.226 },
      { label: "10 oz bottle", oz: 10 },
    ],
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until spray has dried (sod farms: 24 hours)",
    applicationNotes: [
        "Apply to actively growing weeds — mature or hardened-off weeds may not be controlled",
        "Weed control is faster when soil temperatures are above 65°F and soil moisture is adequate",
        "Expect weed yellowing within hours; full control takes 1–4 weeks depending on weed and conditions",
        "Apply mixed spray solution within 5 days of mixing to avoid product degradation",
        "Irrigate before application if turf is under drought stress — do not irrigate until spray has dried",
        "Rainfall before spray dries may reduce control and require retreatment",
        "Spot treatments on St. Augustinegrass above 90°F may cause temporary growth regulation — turf recovers after mowing",
        "For high weed pressure, add non-ionic surfactant (NIS) at 0.25% v/v to spray solution",
        "For difficult-to-control weeds, methylated seed oil (MSO) at 0.25–0.5% v/v may improve control"    
    ],
    restrictions: [
        "Do not apply if frost/freeze expected within 48 hours",
        "Do not use surfactant above 90°F",
        "Do not apply to stressed turf with adjuvant",
        "Do not apply to golf course greens or collars",
        "Do not apply by air or through any irrigation system",
        "Do not apply to turf exhibiting injury from previous pesticide applications",
        "Do not mow until spray has dried after application — do not transfer clippings to non-target areas",
        "Do not plant ornamentals or bedding plants in treated bare areas for at least 30 days after last application",
        "Allow minimum 14 days between broadcast application and overseeding with ryegrass",
        "Max single app: 0.113 oz per 1,000 sq ft",
        "Max annual: 0.17 oz per 1,000 sq ft"
    ],
    labelUrl: "https://bynder.envu.com/m/65d25e1e68990f59/original/Digital_TO_Celsius-WG_label_NA_US_EN.pdf"
  },

  {
    id: "certainty-turf",
    fullName: "Certainty Turf Herbicide, Valent",
    brand: "Valent",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "granule",
    activeIngredients: [
        "Sulfosulfuron 75.0%"
    ],
    genericAlternatives: [
        {
            fullName: "Sertay Herbicide, Atticus",
            activeIngredient: "Sulfosulfuron 75%",
            note: "Same active ingredient and concentration. Typically available at lower cost."
        }
    ],
    mixUnit: "oz",
    perUnit: 1000,
    rateMin: 0.0172,    // 0.75 oz/acre — low end (rescuegrass)
    rateMax: 0.0459,    // 2.0 oz/acre — max single application
    rateDefault: 0.0287, // 1.25 oz/acre — standard sedge/kyllinga rate
    rateTiers: [
        { label: "Low",     ozPer1k: 0.0172 },
        { label: "Medium",  ozPer1k: 0.0287 },
        { label: "High",    ozPer1k: 0.0459 }
    ],
    annualMaxPer1k: 0.0611,   // 2.66 oz/acre
    waterPerUnit: 2,           // fixed — 2 gal per 1,000 sq ft
    surfactant: "NIS at 0.25–0.5% v/v (required)",
    rainfastHours: 2,
    turfTypes: [
        "Bahiagrass",
        "Bermudagrass",
        "Big Bluestem",
        "Buffalograss",
        "Centipedegrass",
        "Indiangrass",
        "Kikuyugrass",
        "Little Bluestem",
        "Seashore Paspalum",
        "St. Augustinegrass",
        "Switchgrass",
        "Zoysiagrass"
    ],
    turfNotes: [
        "St. Augustinegrass and Seashore Paspalum are more sensitive — test on small area before wide-scale use",
        "May cause temporary chlorosis on all listed warm-season grasses"
    ],
    notSafeTurf: [
        "Annual Bluegrass / Poa annua (actively removed)",
        "Kentucky Bluegrass (not listed as safe)",
        "Perennial Ryegrass (actively removed)",
        "Tall Fescue (this product actively removes it)"
    ],
    targetWeeds: [
      { label: "Barley, Little", ids: ["barley-little"] },
      { label: "Bedstraw, Catchweed", ids: ["bedstraw-catchweed"] },
      { label: "Beggarweed, Florida (Suppression)", ids: ["beggarweed-florida"] },
      { label: "Bentgrass, Creeping", ids: ["creeping-bentgrass-weed-escape"] },
      { label: "Bluegrass, Annual", ids: ["annual-bluegrass"] },
      { label: "Bluegrass, Bulbous", ids: ["bluegrass-bulbous"] },
      { label: "Bluegrass, Roughstalk", ids: ["bluegrass-roughstalk"] },
      { label: "Burweed, Lawn", ids: ["lawn-burweed"] },
      { label: "Buttercup", ids: ["buttercup-corn"] },
      { label: "Buttonweed (Suppression)", ids: ["virginia-buttonweed"] },
      { label: "Chamber Bitter", ids: ["chamberbitter"] },
      { label: "Chamomile, Mayweed", ids: ["mayweed"] },
      { label: "Chickweed, Common", ids: ["chickweed"] },
      { label: "Clover, White", ids: ["white-clover"] },
      { label: "Crowfootgrass", ids: ["crowfootgrass"] },
      { label: "Dallisgrass (Suppression)", ids: ["dallisgrass"] },
      { label: "Dandelion", ids: ["dandelion"] },
      { label: "Dichondra, Carolina", ids: ["dichondra"] },
      { label: "Fescue, Tall", ids: ["fescue-weed-escape"] },
      { label: "Garlic, Wild", ids: ["wild-garlic"] },
      { label: "Geranium, Carolina (Suppression)", ids: ["geranium-carolina"] },
      { label: "Henbit (Suppression)", ids: ["henbit"] },
      { label: "Ivy, Ground", ids: ["ground-ivy"] },
      { label: "Johnsongrass", ids: ["johnsongrass"] },
      { label: "Kyllinga, False Green", ids: ["false-green-kyllinga"] },
      { label: "Kyllinga, Fragrant", ids: ["kyllinga-fragrant"] },
      { label: "Kyllinga, Green", ids: ["green-kyllinga"] },
      { label: "Mustard, Tumble", ids: ["jim-hill-mustard"] },
      { label: "Mustard, Wild", ids: ["mustard-wild"] },
      { label: "Nutsedge, Purple", ids: ["nutsedge-purple"] },
      { label: "Nutsedge, Yellow", ids: ["nutsedge-yellow"] },
      { label: "Pennycress, Field", ids: ["pennycress"] },
      { label: "Pennywort, Lawn (Suppression)", ids: ["water-pennywort"] },
      { label: "Quackgrass (Suppression)", ids: ["quackgrass"] },
      { label: "Ryegrass, Perennial", ids: ["ryegrass-perennial"] },
      { label: "Sedge, Globe", ids: ["globe-sedge"] },
      { label: "Sedges, Annual", ids: ["annual-sedge"] },
      { label: "Shepherd's Purse", ids: ["shepherds-purse"] },
      { label: "Violet, Wild", ids: ["violet-common-blue"] },
      { label: "Woodsorrel, Yellow", ids: ["woodsorrel-yellow"] },
    ],
    containerSizes: [
        { label: "1.25 oz bottle", oz: 1.25 }
    ],
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until spray has dried (agricultural use: 12 hours)",
    applicationNotes: [
        "Apply when target weeds are actively growing — do not mow for at least 2 days before and 2 days after application",
        "Weed growth stops within 24 hours; visible yellowing or browning typically appears within 2–3 weeks",
        "Warm, moist conditions after application accelerate control — cold or dry conditions delay it",
        "Weeds under drought stress are less susceptible — irrigate before application if needed",
        "Nonionic surfactant (NIS) required at 0.25–0.5% v/v — use only NIS with at least 90% active ingredient",
        "May cause temporary chlorosis on all listed turf types — more pronounced on St. Augustinegrass and Seashore Paspalum",
        "On cool-season turf, apply only when actively growing and mowing is still required"    
    ],
    restrictions: [
        "Do not apply through air or any irrigation system",
        "Do not apply directly to or within 4 feet of golf course putting greens",
        "Do not use nonionic surfactants that lower spray solution pH below 5",
        "Sequential applications must be at least 3 weeks apart (4+ weeks for sedge control)",
        "Rainfastness: 2 hours — repeat if rainfall within 2 hours of application",
        "Max single application: 2.0 oz/acre (0.0459 oz/1,000 sq ft)",
        "Max annual: 2.66 oz/acre (0.0611 oz/1,000 sq ft)",
        "Test on St. Augustinegrass and Seashore Paspalum before wide-scale use"
    ],
    labelUrl: "https://www.cdms.net/ldat/ldDIQ000.pdf"
  },

  {
    id: "dimension-2ew",
    fullName: "Dimension 2EW Specialty Herbicide",
    brand: "Corteva Agriscience",
    category: "herbicide",
    type: ["pre-emergent"],
    formulation: "emulsifiable concentrate",
    activeIngredients: ["Dithiopyr 24%"],
    genericAlternatives: [
      {
        fullName: "Dithiopyr 2EW, quali-Pro",
        activeIngredient: "Dithiopyr 24%",
        note: "Same active ingredient and concentration. Typically available at lower cost."
      },
      {
        fullName: "Dithiopyr 2 EW, RightLine",
        activeIngredient: "Dithiopyr 24%",
        note: "Same active ingredient and concentration. Typically available at lower cost."
      }
    ],
    mixUnit: "fl oz",
    perUnit: 1000,
    rateMin: 0.37,
    rateMax: 0.73,
    rateDefault: 0.5,
    annualMaxPer1k: 2.2,
    waterPerUnit: 0.5,
    turfTypes: [
      "Bahiagrass",
      "Bermudagrass",
      "Buffalograss",
      "Carpetgrass",
      "Centipedegrass",
      "Creeping Bentgrass",
      "Fine Fescue",
      "Kentucky Bluegrass",
      "Kikuyugrass",
      "Perennial Ryegrass",
      "Seashore Paspalum",
      "St. Augustinegrass",
      "Tall Fescue",
      "Zoysiagrass"
    ],
    notSafeTurf: [
      "Colonial Bentgrass (Agrostis tenuis) — do not apply",
      "Tifgreen (328) Bermudagrass — do not apply"
    ],
    targetWeeds: [
      { label: "Barley", ids: ["wild-barley"] },
      { label: "Barnyardgrass", ids: ["barnyardgrass"] },
      { label: "Bittercress", ids: ["hairy-bittercress"] },
      { label: "Bluegrass, Annual", ids: ["annual-bluegrass"] },
      { label: "Brome", ids: ["brome"] },
      { label: "Carpetweed", ids: ["carpetweed"] },
      { label: "Chickweed", ids: ["chickweed"] },
      { label: "Crabgrass, Large", ids: ["crabgrass-large"] },
      { label: "Crabgrass, Smooth", ids: ["crabgrass-smooth"] },
      { label: "Crabgrass, Southern", ids: ["crabgrass-hairy"] },
      { label: "Crowfootgrass", ids: ["crowfootgrass"] },
      { label: "Dallisgrass (Seedling)", ids: ["dallisgrass"] },
      { label: "Dandelion, Common", ids: ["dandelion"] },
      { label: "Foxtail, Giant", ids: ["foxtail-giant"] },
      { label: "Foxtail, Green", ids: ["foxtail-green"] },
      { label: "Foxtail, Yellow", ids: ["foxtail-yellow"] },
      { label: "Geranium, Carolina", ids: ["geranium-carolina"] },
      { label: "Goosegrass", ids: ["goosegrass"] },
      { label: "Henbit", ids: ["henbit"] },
      { label: "Kikuyugrass", ids: ["kikuyugrass"] },
      { label: "Knotweed, Prostrate", ids: ["knotweed"] },
      { label: "Lespedeza, Common", ids: ["japanese-clover"] },
      { label: "Marestail", ids: ["canada-fleabane"] },
      { label: "Mary's Grass (Japanese Stiltgrass)", ids: ["stiltgrass"] },
      { label: "Medic, Black", ids: ["black-medic"] },
      { label: "Mulberry Weed", ids: ["mulberry-weed"] },
      { label: "Mustard", ids: ["mustard"] },
      { label: "Oats, Wild", ids: ["wild-oats"] },
      { label: "Oxalis, Buttercup", ids: ["oxalis-buttercup"] },
      { label: "Parsley-Piert", ids: ["parsley-piert"] },
      { label: "Pigweed, Redroot", ids: ["pigweed-redroot"] },
      { label: "Pineappleweed", ids: ["pineappleweed"] },
      { label: "Purslane, Common", ids: ["purslane"] },
      { label: "Rocket, London", ids: ["london-rocket"] },
      { label: "Ryegrass (Annual & Perennial)", ids: ["ryegrass-annual", "ryegrass-perennial"] },
      { label: "Sandbur", ids: ["sandbur"] },
      { label: "Shepherdspurse", ids: ["shepherds-purse"] },
      { label: "Smutgrass", ids: ["smutgrass"] },
      { label: "Southwestern Cupgrass", ids: ["southwestern-cupgrass"] },
      { label: "Sowthistle", ids: ["common-sowthistle"] },
      { label: "Speedwell, Corn", ids: ["speedwell-corn"] },
      { label: "Spurge, Garden", ids: ["garden-spurge"] },
      { label: "Spurge, Prostrate", ids: ["spreading-spurge"] },
      { label: "Spurge, Spotted", ids: ["spotted-spurge"] },
      { label: "Willowherb", ids: ["willowherb"] },
      { label: "Woodsorrel, Creeping", ids: ["woodsorrel-creeping"] },
      { label: "Woodsorrel, Yellow", ids: ["woodsorrel-yellow"] },
    ],
    containerSizes: [
      { label: "64 fl oz bottle", oz: 64 },
      { label: "2.5 gal jug", oz: 320 }
    ],
    EPAtoxicityLevel: "Warning (Category II)",
    reentryInterval: "12 hours",
    applicationNotes: [
      "Primarily a pre-emergent herbicide. Apply before weed seed germination for best results. Activated by 0.5 inch or more of rainfall or irrigation.",
      "Also provides post-emergent control of crabgrass up to the 3–5 tiller stage. A non-ionic surfactant at 0.25% v/v is recommended for improved post-emergent control past the 5-leaf stage.",
      "When targeting crabgrass post-emergently, delay irrigation 6 hours after application; apply at least 0.5 inch of water when using for pre-emergent residual control.",
      "Do not mow within 2 days before or after application when targeting crabgrass post-emergently.",
      "Apply in a minimum of 20 gallons of water per acre (approximately 0.5 gal per 1,000 sq ft).",
      "Certain creeping bentgrass varieties (Cohansey, Carmen, Seaside, Washington) and all colonial bentgrass (Agrostis tenuis) may be injured — do not apply to these.",
      "Certain fine fescue varieties are sensitive to this product — consult the full label for the complete list before applying to fine fescue.",
      "Do not apply to golf course putting greens."
    ],
    restrictions: [
      "Do not apply more than 0.73 fl oz per 1,000 sq ft per application.",
      "Do not apply more than 2.2 fl oz per 1,000 sq ft per year.",
      "Do not apply through any type of irrigation system (chemigation prohibited).",
      "Do not harvest sod until 3 months or longer after application.",
      "Do not reseed, overseed, or sprig treated areas within 3 months of a single application, or within 4 months after sequential applications exceeding 0.73 fl oz per 1,000 sq ft.",
      "Do not use turf clippings from treated areas as mulch around vegetables or fruit trees.",
      "New York State: Do not exceed 0.73 fl oz per 1,000 sq ft per year. Nassau and Suffolk counties NY: Do not exceed 0.37 fl oz per 1,000 sq ft per year."
    ],
    labelUrl: "https://www.cdms.net/ldat/ld7ND002.pdf"
  },

  {
    id: "drive-xlr8",
    fullName: "Drive XLR8 Herbicide, BASF",
    brand: "BASF",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "liquid",
    activeIngredients: [
      "Dimethylamine salt of quinclorac 18.92%"
    ],
    genericAlternatives: [
      {
        fullName: "Quinclorac 1.5L, Quali-Pro",
        activeIngredient: "Dimethylamine salt of quinclorac 17.79%",
        note: "Different concentration of the same active ingredient. Typically available at lower cost."
      },
      {
        fullName: "Quinclorac 1.5L, Prime Source",
        activeIngredient: "Dimethylamine salt of quinclorac 18.92%",
        note: "Same active ingredient and concentration. Typically available at lower cost."
      }
    ],
    mixUnit: "fl oz",
    perUnit: 1000,
    rateMin: 0.5,     // fl oz per 1000 sq ft — creeping bentgrass split app low end
    rateMax: 1.45,    // fl oz per 1000 sq ft — standard broadcast rate per label Table 3
    rateDefault: 1.45,
    turfRates: [
      {
        turfGroup: [
          "Annual Bluegrass", "Annual Ryegrass", "Bermudagrass",
          "Buffalograss", "Chewing's Fescue", "Fine Fescue",
          "Hard Fescue", "Kentucky Bluegrass", "Perennial Ryegrass",
          "Red Fescue", "Rough Bluegrass", "Tall Fescue", "Zoysiagrass"
        ],
        rateMin: 1.45,
        rateMax: 1.45   // single application rate per label; no low/high range for standard turf
      },
      {
        turfGroup: ["Creeping Bentgrass"],
        rateMin: 0.5,
        rateMax: 1.0,
        notes: "Apply in 2–3 split applications 14–21 days apart; minimum 0.65 fl oz in California"
      }
    ],
    annualMaxPer1k: 2.9,   // fl oz per 1000 sq ft (128 fl oz per acre per label)
    waterPerUnit: 0.5,      // gal per 1000 sq ft — label minimum (20 gal/acre = 0.46 gal/1000; label rounds to 0.5)
    turfTypes: [
      "Annual Bluegrass",
      "Annual Ryegrass",
      "Bermudagrass",
      "Buffalograss",
      "Chewing's Fescue",
      "Creeping Bentgrass",
      "Fine Fescue",
      "Hard Fescue",
      "Kentucky Bluegrass",
      "Perennial Ryegrass",
      "Red Fescue",
      "Rough Bluegrass",
      "Tall Fescue",
      "Zoysiagrass"
    ],
    notSafeTurf: [
      "Bahiagrass",
      "Carpetgrass",
      "Centipedegrass",
      "Colonial Bentgrass",
      "Dichondra",
      "Seashore Paspalum",
      "Seaside Bentgrass",
      "St. Augustinegrass"
    ],
    targetWeeds: [
      { label: "Barnyardgrass", ids: ["barnyardgrass"] },
      { label: "Bindweed, Field", ids: ["field-bindweed"] },
      { label: "Clover, Hop", ids: ["hop-clover-large"] },
      { label: "Clover, Red", ids: ["red-clover"] },
      { label: "Clover, White", ids: ["white-clover"] },
      { label: "Crabgrass, Large", ids: ["crabgrass-large"] },
      { label: "Crabgrass, Smooth", ids: ["crabgrass-smooth"] },
      { label: "Daisy, English", ids: ["english-daisy"] },
      { label: "Dandelion, Common", ids: ["dandelion"] },
      { label: "Dollarweed", ids: ["water-pennywort"] },
      { label: "Foxtail, Giant", ids: ["foxtail-giant"] },
      { label: "Foxtail, Green", ids: ["foxtail-green"] },
      { label: "Foxtail, Yellow", ids: ["foxtail-yellow"] },
      { label: "Geranium, Carolina", ids: ["geranium-carolina"] },
      { label: "Horseweed", ids: ["canada-fleabane"] },
      { label: "Kikuyugrass", ids: ["kikuyugrass"] },
      { label: "Medic, Black", ids: ["black-medic"] },
      { label: "Morningglory spp.", ids: ["morningglory"] },
      { label: "Signalgrass, Broadleaf", ids: ["signalgrass-broadleaf"] },
      { label: "Speedwell, Common", ids: ["speedwell-common"] },
      { label: "Speedwell, Slender", ids: ["speedwell-slender"] },
      { label: "Speedwell, Thymeleaf", ids: ["speedwell-thymeleaf"] },
      { label: "Torpedograss", ids: ["torpedograss"] },
      { label: "Violet, Wild", ids: ["wild-violet"] },
    ],
    containerSizes: [
      { label: "64 fl oz bottle", oz: 64 },
      { label: "2.5 gal jug", oz: 320 }
    ],
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until spray has dried (agricultural use: 12 hours)",
    applicationNotes: [
      "Apply to actively growing weeds — do not apply when weeds are under stress from drought, heat, recent mowing, or prior herbicide applications",
      "Methylated seed oil (MSO) at 0.55 fl oz per 1000 sq ft is required in the spray mix for consistent control; crop oil concentrate (COC) or a quality surfactant may be substituted if MSO is unavailable",
      "Do not mow 2 days before or after application; leave clippings from the first three mowings on the treated area",
      "Do not water or irrigate for 24 hours after application; if no rainfall occurs within 2–7 days, irrigate at least 0.5 inch",
      "For creeping bentgrass: use 2–3 split applications at 0.5–1.0 fl oz per 1000 sq ft, 14–21 days apart (minimum 0.65 fl oz in California)",
      "For kikuyugrass and torpedograss: make 2 sequential applications at 1.0 fl oz per 1000 sq ft, then a third application at up to 0.90 fl oz, all 14–21 days apart",
      "Apply as medium or coarser spray at 20–40 psi; do not release spray above 30 inches from the ground",
      "Chelated iron or sprayable soluble nitrogen fertilizer added to the mix may reduce slight yellowing that can occur on bermudagrass and zoysiagrass"
    ],
    restrictions: [
      "Do not apply to Bahiagrass, carpetgrass, centipedegrass, colonial bentgrass, seaside bentgrass, dichondra, or St. Augustinegrass",
      "Do not apply to fine fescue unless it is part of a seed blend",
      "Do not apply to golf course collars or greens",
      "Do not apply to drought-stressed turfgrass or drought-stressed weeds",
      "Do not apply to lawns where desirable clovers are present",
      "Do not apply within 4 weeks after seedling emergence of creeping bentgrass, fine fescue blends, Kentucky bluegrass, or perennial ryegrass",
      "Do not apply within 2 weeks before or after seeding or sprigging seashore paspalum",
      "Do not apply in New York except as a spot application",
      "Do not apply by air or through any irrigation system",
      "Do not plant eggplants or tobacco within 12 months in treated areas",
      "Do not plant tomatoes or carrots within 24 months in treated areas",
      "Do not use clippings as mulch or compost around flowers, ornamentals, trees, or in vegetable gardens",
      "Do not apply when wind speeds exceed 10 mph",
      "Max single application: 1.45 fl oz per 1000 sq ft (64 fl oz per acre)",
      "Max annual: 2.9 fl oz per 1000 sq ft (128 fl oz per acre)"
    ],
    labelUrl: "https://www.cdms.net/ldat/ld8LD004.pdf"
  },

  {
    id: "fahrenheit-herbicide",
    fullName: "Fahrenheit Herbicide, Quali-Pro",
    brand: "Quali-Pro",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "granule",
    activeIngredients: [
      "Potassium salt of Dicamba 33.00%",
      "Metsulfuron-methyl 5.00%"
    ],
    genericAlternatives: [],
    mixUnit: "oz",
    perUnit: 1000,
    rateMin: 0.069,
    rateMax: 0.275,
    rateDefault: 0.138,
    turfRates: [
      {
        turfGroup: ["Bermudagrass", "St. Augustinegrass", "Zoysiagrass"],
        rateMin: 0.069,
        rateMax: 0.275
      },
      {
        turfGroup: ["Centipedegrass"],
        rateMin: 0.069,
        rateMax: 0.138
      }
    ],
    rateTiers: [
      { label: "Low",    ozPer1k: 0.069 },
      { label: "Medium", ozPer1k: 0.138 },
      { label: "High",   ozPer1k: 0.275 }
    ],
    annualMaxPer1k: 0.275,
    waterPerUnit: 1,
    turfTypes: [
      "Bermudagrass",
      "Centipedegrass",
      "St. Augustinegrass",
      "Zoysiagrass"
    ],
    notSafeTurf: [
      "Bahiagrass (this product selectively removes it — not a safe turf type)"
    ],
    targetWeeds: [
      { label: "Ryegrass", ids: ["ryegrass-annual", "ryegrass-perennial"], rateRequired: "Low" },
      { label: "Annual fleabane", ids: ["fleabane-annual"], rateRequired: "Low" },
      { label: "Chicory", ids: ["chicory"], rateRequired: "Low" },
      { label: "Field pennycress", ids: ["pennycress"], rateRequired: "Low" },
      { label: "Bittercress", ids: ["hairy-bittercress"], rateRequired: "Low" },
      { label: "Clover (white)", ids: ["white-clover"], rateRequired: "Low" },
      { label: "Florida beggarweed", ids: ["beggarweed-florida"], rateRequired: "Low" },
      { label: "Black medic", ids: ["black-medic"], rateRequired: "Low" },
      { label: "Common chickweed", ids: ["chickweed"], rateRequired: "Low" },
      { label: "Parsley-piert", ids: ["parsley-piert"], rateRequired: "Low" },
      { label: "Blue mustard", ids: ["blue-mustard"], rateRequired: "Low" },
      { label: "Common dandelion", ids: ["dandelion"], rateRequired: "Low" },
      { label: "Prostrate spurge", ids: ["prostrate-spurge"], rateRequired: "Low" },
      { label: "Bristly mallow", ids: ["bristly-mallow"], rateRequired: "Low" },
      { label: "Corn chamomile", ids: ["chamomile-corn"], rateRequired: "Low" },
      { label: "Redstem filaree", ids: ["filaree-redstem"], rateRequired: "Low" },
      { label: "Buttercup", ids: ["buttercup"], rateRequired: "Low" },
      { label: "Corn cockle", ids: ["corn-cockle"], rateRequired: "Low" },
      { label: "Smoothweed bedstraw", ids: ["bedstraw-smoothweed"], rateRequired: "Low" },
      { label: "Carpetweed", ids: ["carpetweed"], rateRequired: "Low" },
      { label: "Cow cockle", ids: ["cow-cockle"], rateRequired: "Low" },
      { label: "Virginia pepperweed", ids: ["pepperweed-virginia"], rateRequired: "Low" },
      { label: "Carolina geranium", ids: ["geranium-carolina"], rateRequired: "Low" },
      { label: "Creeping beggarweed", ids: ["beggarweed-creeping"], rateRequired: "Low" },
      { label: "Wild buckwheat", ids: ["wild-buckwheat"], rateRequired: "Low" },
      { label: "Catchweed bedstraw", ids: ["bedstraw-catchweed"], rateRequired: "Low" },
      { label: "Dwarf mallow", ids: ["mallow-dwarf"], rateRequired: "Low" },
      { label: "Wild carrot", ids: ["wild-carrot"], rateRequired: "Low" },
      { label: "Annual sowthistle", ids: ["common-sowthistle"], rateRequired: "Medium" },
      { label: "Gromwell", ids: ["gromwell"], rateRequired: "Medium" },
      { label: "Silverleaf nightshade", ids: ["nightshade-silverleaf"], rateRequired: "Medium" },
      { label: "Bitter sneezeweed", ids: ["bitter-sneezeweed"], rateRequired: "Medium" },
      { label: "Ground ivy", ids: ["ground-ivy"], rateRequired: "Medium" },
      { label: "Slender Aster", ids: ["slender-aster"], rateRequired: "Medium" },
      { label: "Bracted plantain", ids: ["bracted-plantain"], rateRequired: "Medium" },
      { label: "Hawkweed", ids: ["hawkweed"], rateRequired: "Medium" },
      { label: "Smooth pigweed", ids: ["pigweed-smooth"], rateRequired: "Medium" },
      { label: "Broadleaf dock", ids: ["dock-broadleaf"], rateRequired: "Medium" },
      { label: "Hemp sesbania", ids: ["hemp-sesbania"], rateRequired: "Medium" },
      { label: "Smallseed falseflax", ids: ["smallseed-falseflax"], rateRequired: "Medium" },
      { label: "Buffalobur", ids: ["buffalobur"], rateRequired: "Medium" },
      { label: "Henbit", ids: ["henbit"], rateRequired: "Medium" },
      { label: "Spiny amaranth", ids: ["spiny-amaranth"], rateRequired: "Medium" },
      { label: "Bull thistle", ids: ["thistle-bull"], rateRequired: "Medium" },
      { label: "Jimsonweed", ids: ["jimsonweed"], rateRequired: "Medium" },
      { label: "Spiny aster", ids: ["spiny-aster"], rateRequired: "Medium" },
      { label: "Burclover", ids: ["burclover"], rateRequired: "Medium" },
      { label: "Knotweed", ids: ["knotweed"], rateRequired: "Medium" },
      { label: "Spotted knapweed", ids: ["spotted-knapweed"], rateRequired: "Medium" },
      { label: "Burcucumber", ids: ["burcucumber"], rateRequired: "Medium" },
      { label: "Lawn burweed (Spurweed)", ids: ["lawn-burweed"], rateRequired: "Medium" },
      { label: "Stinging nettle", ids: ["stinging-nettle"], rateRequired: "Medium" },
      { label: "Common burdock", ids: ["common-burdock"], rateRequired: "Medium" },
      { label: "Lespedeza", ids: ["lespedeza"], rateRequired: "Medium" },
      { label: "Sweet clover", ids: ["sweet-clover"], rateRequired: "Medium" },
      { label: "Common cocklebur", ids: ["cocklebur"], rateRequired: "Medium" },
      { label: "Mayweed", ids: ["mayweed"], rateRequired: "Medium" },
      { label: "Tansy mustard", ids: ["tansy-mustard"], rateRequired: "Medium" },
      { label: "Common evening primrose", ids: ["evening-primrose-common"], rateRequired: "Medium" },
      { label: "Milk thistle", ids: ["milk-thistle"], rateRequired: "Medium" },
      { label: "Teasel", ids: ["teasel"], rateRequired: "Medium" },
      { label: "Common lambsquarters", ids: ["lambsquarters"], rateRequired: "Medium" },
      { label: "Milkweed (various)", ids: ["milkweed"], rateRequired: "Medium" },
      { label: "Treacle mustard", ids: ["treacle-mustard"], rateRequired: "Medium" },
      { label: "Common mallow", ids: ["mallow-common"], rateRequired: "Medium" },
      { label: "Miners lettuce", ids: ["miners-lettuce"], rateRequired: "Medium" },
      { label: "Tropic croton", ids: ["tropic-croton"], rateRequired: "Medium" },
      { label: "Common purslane", ids: ["purslane"], rateRequired: "Medium" },
      { label: "Morningglory (various)", ids: ["morningglory"], rateRequired: "Medium" },
      { label: "Tumble mustard", ids: ["jim-hill-mustard"], rateRequired: "Medium" },
      { label: "Common ragweed", ids: ["ragweed"], rateRequired: "Medium" },
      { label: "Mouseear chickweed", ids: ["mouseear-chickweed"], rateRequired: "Medium" },
      { label: "Velvetleaf", ids: ["abutilon"], rateRequired: "Medium" },
      { label: "Common yarrow", ids: ["yarrow"], rateRequired: "Medium" },
      { label: "Musk thistle", ids: ["thistle-musk"], rateRequired: "Medium" },
      { label: "Waterhemlock", ids: ["waterhemlock"], rateRequired: "Medium" },
      { label: "Crown vetch", ids: ["crown-vetch"], rateRequired: "Medium" },
      { label: "Pigweed (various)", ids: ["pigweed"], rateRequired: "Medium" },
      { label: "White cockle", ids: ["cockle-white"], rateRequired: "Medium" },
      { label: "Cutleaf evening primrose", ids: ["evening-primrose-cutleaf"], rateRequired: "Medium" },
      { label: "Plantain", ids: ["plantain"], rateRequired: "Medium" },
      { label: "Wild celery", ids: ["wild-celery"], rateRequired: "Medium" },
      { label: "Curly dock", ids: ["dock-curly"], rateRequired: "Medium" },
      { label: "Prickly sida", ids: ["prickly-sida"], rateRequired: "Medium" },
      { label: "Wild garlic", ids: ["wild-garlic"], rateRequired: "Medium" },
      { label: "English daisy", ids: ["english-daisy"], rateRequired: "Medium" },
      { label: "Wild lettuce", ids: ["wild-lettuce-tall"], rateRequired: "Medium" },
      { label: "Florida betony", ids: ["florida-betony"], rateRequired: "Medium" },
      { label: "Redroot pigweed", ids: ["pigweed-redroot"], rateRequired: "Medium" },
      { label: "Wild radish", ids: ["wild-radish"], rateRequired: "Medium" },
      { label: "Florida pusley", ids: ["florida-pusley"], rateRequired: "Medium" },
      { label: "Woodsorrel", ids: ["woodsorrel"], rateRequired: "Medium" },
      { label: "Giant ragweed", ids: ["giant-ragweed"], rateRequired: "Medium" },
      { label: "Sheep sorrel", ids: ["red-sorrel"], rateRequired: "Medium" },
      { label: "Woolly croton", ids: ["croton-woolly"], rateRequired: "Medium" },
      { label: "Goldenrod", ids: ["goldenrod"], rateRequired: "Medium" },
      { label: "Shepherdspurse", ids: ["shepherds-purse"], rateRequired: "Medium" },
      { label: "Yellow starthistle", ids: ["starthistle-yellow"], rateRequired: "Medium" },
      { label: "Bahiagrass", ids: ["bahiagrass"], rateRequired: "Medium" },
      { label: "Black nightshade", ids: ["nightshade-black"], rateRequired: "High" },
      { label: "Foxtail", ids: ["foxtail"], rateRequired: "High" },
      { label: "Prostrate knotweed", ids: ["knotweed"], rateRequired: "High" },
      { label: "Bracken fern", ids: ["bracken-fern"], rateRequired: "High" },
      { label: "Hoary cress (whitetop)", ids: ["hoary-cress"], rateRequired: "High" },
      { label: "Russian thistle", ids: ["russian-thistle"], rateRequired: "High" },
      { label: "Brazil pusley", ids: ["brazil-pusley"], rateRequired: "High" },
      { label: "Horsenettle", ids: ["horsenettle"], rateRequired: "High" },
      { label: "Sicklepod", ids: ["sicklepod"], rateRequired: "High" },
      { label: "Buckhorn plantain", ids: ["plantain-buckhorn"], rateRequired: "High" },
      { label: "Horseweed", ids: ["canada-fleabane"], rateRequired: "High" },
      { label: "Southern sida", ids: ["southern-sida"], rateRequired: "High" },
      { label: "Canada thistle", ids: ["thistle-canada"], rateRequired: "High" },
      { label: "Ironweed", ids: ["ironweed"], rateRequired: "High" },
      { label: "Tropical soda apple", ids: ["tropical-soda-apple"], rateRequired: "High" },
      { label: "Common groundsel", ids: ["groundsel"], rateRequired: "High" },
      { label: "Jerusalem artichoke", ids: ["jerusalem-artichoke"], rateRequired: "High" },
      { label: "Trumpetcreeper", ids: ["trumpetcreeper"], rateRequired: "High" },
      { label: "Kochia", ids: ["kochia"], rateRequired: "High" },
      { label: "Waterhemp", ids: ["waterhemp"], rateRequired: "High" },
      { label: "Creeping woodsorrel", ids: ["woodsorrel-creeping"], rateRequired: "High" },
      { label: "Pennsylvania smartweed", ids: ["smartweed-pennsylvania"], rateRequired: "High" },
      { label: "Wild mustard", ids: ["mustard-wild"], rateRequired: "High" },
      { label: "Dogfennel", ids: ["dogfennel"], rateRequired: "High" },
      { label: "Perennial sowthistle", ids: ["sowthistle-perennial"], rateRequired: "High" },
      { label: "Wormwood (common)", ids: ["wormwood-common"], rateRequired: "High" },
      { label: "Dollarweed", ids: ["water-pennywort"], rateRequired: "High" },
      { label: "Pokeweed", ids: ["pokeweed"], rateRequired: "High" },
      { label: "Wormwood (Louisiana)", ids: ["wormwood-louisiana"], rateRequired: "High" },
      { label: "Field bindweed", ids: ["field-bindweed"], rateRequired: "High" },
      { label: "Poorjoe", ids: ["poorjoe"], rateRequired: "High" },
      { label: "Yankeeweed", ids: ["yankeeweed"], rateRequired: "High" }
    ],
    
    containerSizes: [
      { label: "6 oz bottle", oz: 6 }
    ],
    EPAtoxicityLevel: "WARNING",
    reentryInterval: "Until spray has dried (agricultural use: 24 hours)",
    applicationNotes: [
      "Apply to actively growing weeds — weed control is faster when soil temperatures are above 60°F and weeds are not under moisture stress",
      "For spot applications with a backpack or hand-held sprayer, add 0.2 oz per 1 gallon of water and apply uniformly over 1,000 sq ft",
      "For broadcast applications, use 20–80 gallons of water per acre at 30–40 psi; use higher volumes for dense weed populations",
      "A non-ionic surfactant (NIS) with at least 80% active content at 0.25% v/v (1 qt per 100 gal) may be added for improved control — use with caution above 85°F or when turf is stressed",
      "Spray solution pH near 7.0 is ideal; acidic sprays below pH 6.0 must be used within 24 hours or a suitable buffer added",
      "Maintain continuous agitation in spray tank — settling will occur if agitation stops; re-agitate thoroughly before resuming",
      "Some temporary chlorosis or growth reduction may occur on listed turf types; more pronounced on St. Augustinegrass above 85°F",
      "For Bermudagrass overseeded with ryegrass, allow at least 60 days between broadcast application and overseeding"
    ],
    restrictions: [
      "Do not apply more than 12 oz per acre per calendar year",
      "Do not apply to turfgrass less than one year old",
      "Do not apply to turfgrass under stress from high temperatures (above 85°F), drought, poor fertility, disease, or insects",
      "Do not use on grasses other than St. Augustinegrass, Bermudagrass, Centipedegrass, and Zoysiagrass — injury may occur on unlisted grasses",
      "Do not apply to Dichondra lawns or where desirable clovers are present",
      "Do not apply to golf course greens or collars",
      "Do not apply through any type of irrigation system or by aircraft",
      "Do not mow immediately after application; do not transfer clippings to non-target areas",
      "Do not plant ornamental shrubs or trees in treated areas for at least 1 year, or bedding plants for at least 2 years after last application",
      "Apply in wind of 10 mph or less; maintain 25-foot buffer from sensitive areas and desirable vegetation",
      "Rainfall or irrigation before spray dries may reduce efficacy and require retreatment"
    ],
    labelUrl: "https://www.controlsolutionsinc.com/hubfs/Specimen%20Labels/Specimen-Fahrenheit-53883-387.pdf?hsLang=en"
  },

  {
    id: "msma-target-6-plus",
    fullName: "MSMA Target 6 Plus, Luxembourg-Pamol",
    brand: "Luxembourg-Pamol",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "liquid",
    activeIngredients: [
      "Monosodium Acid Methanearsonate (MSMA) 48.30%"
    ],
    genericAlternatives: [],
    mixUnit: "fl oz",
    perUnit: 1000,
    rateMin: 1.0,    // fl oz per 1000 sq ft — standard rate for all listed turf
    rateMax: 2.0,    // fl oz per 1000 sq ft — upper range for Bermudagrass and Zoysiagrass
    rateDefault: 1.0,
    turfRates: [
      {
        turfGroup: ["Bermudagrass", "Zoysiagrass"],
        rateMin: 1.0,
        rateMax: 2.0
      },
      {
        turfGroup: ["Kentucky Bluegrass"],
        rateMin: 1.0,
        rateMax: 1.0
      }
    ],
    waterPerUnit: 1.0,   // gal per 1000 sq ft — label minimum (label range: 1 to 2.5 gal per 1000 sq ft)
    turfTypes: [
      "Bermudagrass",
      "Kentucky Bluegrass",
      "Zoysiagrass"
    ],
    notSafeTurf: [
      "Bahiagrass (this product removes it — do not use on bahiagrass lawns)",
      "Carpetgrass",
      "Centipedegrass",
      "Creeping Bentgrass (injury may result)",
      "Dichondra",
      "Fine Fescue (injury may result)",
      "St. Augustinegrass",
      "Tall Fescue (injury may result)"
    ],
    targetWeeds: [
      { label: "Bahiagrass", ids: ["bahiagrass"] },
      { label: "Barnyardgrass", ids: ["barnyardgrass"] },
      { label: "Brachiaria spp.", ids: ["signalgrass"] },
      { label: "Chickweed", ids: ["chickweed"] },
      { label: "Cocklebur", ids: ["cocklebur"] },
      { label: "Crabgrass, Smooth and Large", ids: ["crabgrass-large", "crabgrass-smooth"] },
      { label: "Dallisgrass", ids: ["dallisgrass"] },
      { label: "Goosegrass", ids: ["goosegrass"] },
      { label: "Johnsongrass", ids: ["johnsongrass"] },
      { label: "Nutsedge", ids: ["nutsedge-purple", "nutsedge-yellow"] },
      { label: "Pigweed", ids: ["pigweed"] },
      { label: "Puncture Vine", ids: ["puncturevine"] },
      { label: "Sandbur", ids: ["sandbur"] },
      { label: "Wood Sorrel", ids: ["woodsorrel"] },
    ],
    containerSizes: [
      { label: "2.5 gal jug", oz: 320 }
    ],
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until product has been washed into the soil (agricultural use: 12 hours)",
    applicationNotes: [
      "⚠️ Only approved for cotton fields, golf courses, sod farms, and highway rights-of-way.",
      "Mow turfgrass to a height of 1 to 1½ inches before treatment to improve spray coverage of weeds",
      "This product contains a built-in surfactant — do not add additional surfactant to the spray tank",
      "Apply during warm weather when temperatures are between 80–90°F and weeds are actively growing",
      "Mix in 1 to 2.5 gallons of water per 1000 sq ft; apply uniformly and thoroughly to wet all undesirable plants",
      "Two or more repeat treatments at 14-day intervals may be necessary for full control; do not repeat prior to 10 days after previous treatment",
      "Do not water treated turf for at least 24 hours after application",
      "Turfgrass may be temporarily discolored after application — bermudagrass, Kentucky bluegrass, and zoysiagrass have shown tolerance and recovery with proper application",
    ],
    restrictions: [
      "⚠️ Not for residential use",
      "Do not apply to St. Augustinegrass, carpetgrass, centipedegrass, or dichondra",
      "Do not apply to bentgrasses or fescues — injury may result",
      "Do not apply through any irrigation system",
      "Do not water turf for at least 24 hours after application",
      "Do not reseed treated areas until 2 weeks after the last application",
      "Do not repeat applications prior to 10 days after the previous treatment",
      "Do not make more than 1 broadcast application per year — all additional applications must be spot treatments only",
      "Do not make more than 4 total applications of MSMA (or DSMA, or a combination) per year",
      "Keep children and domestic animals off treated areas until the product has been washed into the soil",
    ],
    labelUrl: "https://www.cdms.net/ldat/ldULB000.pdf"
  },

  {
    id: "tnex",
    fullName: "T-NEX, Quali-Pro",
    brand: "Control Solutions Inc. (Quali-Pro)",
    category: "plant-growth-regulator",
    type: "plant-growth-regulator",
    formulation: "Micro Emulsion Concentrate (MEC)",
    activeIngredients: ["Trinexapac-ethyl 12%"],
    genericAlternatives: [
      {
        fullName: "Primo MAXX, Syngenta",
        activeIngredient: "Trinexapac-ethyl 11.3%",
        note: "Same active ingredient at a slightly lower concentration. Rates are functionally equivalent at labeled use volumes."
      },
      {
        fullName: "Pramaxis MEC, Atticus",
        activeIngredient: "Trinexapac-ethyl 11.3%",
        note: "Same active ingredient at a slightly lower concentration. Rates are functionally equivalent at labeled use volumes."
      },
      {
        fullName: "Trin-Pac Select, Prime Source",
        activeIngredient: "Trinexapac-ethyl 11.3%",
        note: "Same active ingredient at a slightly lower concentration. Rates are functionally equivalent at labeled use volumes."
      }
    ],
    mixUnit: "fl oz",
    perUnit: "1000 sq ft",
    rateMin: 0.10,
    rateMax: 1.0,
    rateDefault: 0.5,
    turfRates: [
      { turfGroup: ["bahiagrass"],         rateMin: 1.0,   rateMax: 1.0   },
      { turfGroup: ["bentgrass"],          rateMin: 0.75,  rateMax: 0.75  },
      { turfGroup: ["bermudagrass"],       rateMin: 0.25,  rateMax: 0.75  },
      { turfGroup: ["bluegrass"],          rateMin: 0.60,  rateMax: 0.60  },
      { turfGroup: ["buffalograss"],       rateMin: 1.0,   rateMax: 1.0   },
      { turfGroup: ["carpetgrass"],        rateMin: 0.25,  rateMax: 0.40  },
      { turfGroup: ["centipedegrass"],     rateMin: 0.50,  rateMax: 0.50  },
      { turfGroup: ["fescue"],             rateMin: 0.75,  rateMax: 1.0   },
      { turfGroup: ["kikuyugrass"],        rateMin: 0.30,  rateMax: 0.50  },
      { turfGroup: ["ryegrass"],           rateMin: 1.0,   rateMax: 1.0   },
      { turfGroup: ["seashore-paspalum"],  rateMin: 0.375, rateMax: 0.375 },
      { turfGroup: ["st-augustinegrass"],  rateMin: 0.10,  rateMax: 0.15  },
      { turfGroup: ["zoysiagrass"],        rateMin: 0.25,  rateMax: 0.25  }
    ],
    annualMaxPer1k: 7.0,
    waterPerUnit: 1,
    turfTypes: [
      "bahiagrass",
      "bentgrass",
      "bermudagrass",
      "bluegrass",
      "buffalograss",
      "carpetgrass",
      "centipedegrass",
      "fescue",
      "kikuyugrass",
      "ryegrass",
      "seashore-paspalum",
      "st-augustinegrass",
      "zoysiagrass"
    ],
    notSafeTurf: [],
    targetWeeds: [],
    containerSizes: [
      { label: "2.5 gallons (320 fl oz)", oz: 320 }
    ],
    EPAtoxicityLevel: "III (CAUTION)",
    reentryInterval: "0 days (do not enter without footwear until spray dries)",
    applicationNotes: [
      "T-NEX is a plant growth regulator — it suppresses vertical shoot growth, reduces mowing frequency, improves turf density, and promotes root mass. It does not kill weeds, insects, or diseases.",
      "Active only through foliar absorption — not soil uptake. Watering-in after application is not necessary or beneficial.",
      "Growth suppression begins 3–5 days after application. Expect approximately 50% growth inhibition over a 4-week period at labeled rates.",
      "May cause temporary yellowing approximately one week after application. Apply 0.2–0.5 lb of actual nitrogen per 1,000 sq ft, or a labeled rate of iron, to minimize and reverse discoloration.",
      "Bermudagrass rates vary by cultivar: use 0.25 fl oz/1,000 sq ft for hybrid cultivars (Tifdwarf, Tifgreen, other hybrids); use 0.75 fl oz/1,000 sq ft for common bermudagrass. The 0.25–0.75 range shown covers all cultivars — use the lower end for hybrid/fine-textured varieties.",
      "St. Augustinegrass is especially sensitive — use only 0.10–0.15 fl oz per 1,000 sq ft. Do not exceed this range.",
      "Mow either 4 hours after application or 1 hour before application to minimize phytotoxicity risk.",
      "During high-fertility periods or spring flushes, increase the rate up to 50% above the labeled rate for adequate suppression.",
      "For extended growth suppression of up to 8 weeks, a maximum of twice the recommended rate may be applied if temporary discoloration can be tolerated.",
      "Repeat applications are permitted throughout the growing season. Do not exceed 7.0 fl oz per 1,000 sq ft total per year.",
      "Suppresses seedhead formation in hybrid bermudagrass when applied before seedhead emergence. Partially suppresses seedheads in annual bluegrass, bahiagrass, buffalograss, carpetgrass, common bermudagrass, Kentucky bluegrass, and tall fescue.",
      "Can suppress basal rot anthracnose at 0.1–0.2 fl oz/1,000 sq ft every 7–14 days. Tank mix with a registered fungicide for optimal disease control.",
      "Apply in 0.5 to 4.0 gallons of finished spray per 1,000 sq ft. Ensure uniform coverage."
    ],
    restrictions: [
      "Do not exceed 7.0 fl oz per 1,000 sq ft total per calendar year.",
      "Do not apply through any type of irrigation system.",
      "Do not apply when weather conditions favor drift from treated areas.",
      "Do not graze treated areas or feed turf clippings to livestock.",
      "Not for use on sod farms in Arizona.",
      "Do not mix with oxidizing agents — hazardous chemical reaction may occur.",
      "Do not allow contact with water bodies or surface water."
    ],
    labelUrl: "https://www.controlsolutionsinc.com/hubfs/Specimen%20Labels/Specimen-TNEX-53883-353.pdf?hsLang=en"
  },

  {
    id: "speedzone-southern-ew",
    fullName: "SpeedZone Southern EW Broadleaf Herbicide for Turf, PBI-Gordon",
    brand: "PBI-Gordon",
    category: "herbicide",
    type: ["post-emergent"],
    formulation: "liquid",  // EW = emulsion in water
    activeIngredients: [
        "2,4-D, 2-ethylhexyl ester 9.02%",
        "Carfentrazone-ethyl 0.47%",
        "Dicamba, acid 0.59%",
        "Dichlorprop-p, 2-ethylhexyl ester 5.19%"
    ],
    genericAlternatives: [],
    mixUnit: "fl oz",
    perUnit: 1000,
    rateMin: 0.7,     // 2 pt/acre; warm-season low end — confirmed by label spot treatment guidance (0.7 fl oz/1,000 sq ft)
    rateMax: 2.2,     // 6 pt/acre; cool-season high end — confirmed by label spot treatment guidance (2.2 fl oz/1,000 sq ft)
    rateDefault: 1.5, // upper limit of warm-season range and lower limit of cool-season range
    turfRates: [
        {
            turfGroup: [
                "Annual Bluegrass",
                "Annual Ryegrass",
                "Bentgrass (mowed at ½ inch or higher)",
                "Fine Fescue",
                "Kentucky Bluegrass",
                "Perennial Ryegrass",
                "Red Fescue",
                "Tall Fescue"
            ],
            rateMin: 1.5,
            rateMax: 2.2   // 4–6 pt/acre per label Table 1
        },
        {
            turfGroup: [
                "Bahiagrass",
                "Bermudagrass",
                "Buffalograss",
                "Centipedegrass",
                "Seashore Paspalum",
                "St. Augustinegrass",  // excluding 'Floratam' and 'Bitterblue' varieties — see notSafeTurf
                "Zoysiagrass"
            ],
            rateMin: 0.7,
            rateMax: 1.5,  // 2–4 pt/acre per label Table 1
            notes: "Do not use on 'Floratam' or 'Bitterblue' varieties of St. Augustinegrass"
        }
    ],
    annualMaxPer1k: 4.41,   // 12 pt/acre (seasonal max) ÷ 43.56; max 2 broadcast applications per year
    waterPerUnit: 1.0,      // spot treatment: 1 gal per 1,000 sq ft; broadcast range: 3–175 gal/acre (0.07–4 gal/1,000 sq ft)
    turfTypes: [
        "Annual Bluegrass",
        "Annual Ryegrass",
        "Bahiagrass",
        "Bentgrass",
        "Bermudagrass",
        "Buffalograss",
        "Centipedegrass",
        "Fine Fescue",
        "Kentucky Bluegrass",
        "Perennial Ryegrass",
        "Red Fescue",
        "Seashore Paspalum",
        "St. Augustinegrass",
        "Tall Fescue",
        "Zoysiagrass"
    ],
    notSafeTurf: [
        "Bentgrass (mowed below ¼ inch)",
        "Bitterblue St. Augustinegrass",
        "Carpetgrass",
        "Dichondra",
        "Floratam St. Augustinegrass",
        "Lawns where desirable clovers are present",
        "Legumes"
    ],
    targetWeeds: [
      { label: "Aster, White Heath & White Prairie", ids: ["aster-white-heath"] },
      { label: "Bedstraw", ids: ["bedstraw"] },
      { label: "Beggarweed, Creeping", ids: ["beggarweed-creeping"] },
      { label: "Bindweed", ids: ["bindweed"] },
      { label: "Black Medic", ids: ["black-medic"] },
      { label: "Broadleaf Plantain", ids: ["plantain-broadleaf"] },
      { label: "Buckhorn Plantain", ids: ["plantain-buckhorn"] },
      { label: "Bull Thistle", ids: ["thistle-bull"] },
      { label: "Burdock, Common", ids: ["common-burdock"] },
      { label: "Buttercup, Creeping", ids: ["buttercup-creeping"] },
      { label: "Carpetweed", ids: ["carpetweed"] },
      { label: "Chickweed", ids: ["chickweed"] },
      { label: "Chicory", ids: ["chicory"] },
      { label: "Cinquefoil", ids: ["cinquefoil"] },
      { label: "Clover", ids: ["clover"] },
      { label: "Cudweed", ids: ["cudweed"] },
      { label: "Curly Dock", ids: ["dock-curly"] },
      { label: "Dandelion", ids: ["dandelion"] },
      { label: "Dayflower", ids: ["dayflower"] },
      { label: "Deadnettle", ids: ["purple-deadnettle"] },
      { label: "Dock", ids: ["dock"] },
      { label: "Dogfennel", ids: ["dogfennel"] },
      { label: "English Daisy", ids: ["english-daisy"] },
      { label: "False Dandelion (Spotted Catsear & Common Catsear)", ids: ["catsear"] },
      { label: "Field Bindweed (Morningglory & Creeping Jenny)", ids: ["field-bindweed"] },
      { label: "Field Oxeye-daisy (Creeping Oxeye)", ids: ["oxeye-daisy"] },
      { label: "Filaree, Whitestem & Redstem", ids: ["filaree-whitestem", "filaree-redstem"] },
      { label: "Florida Betony", ids: ["florida-betony"] },
      { label: "Florida Pusley", ids: ["florida-pusley"] },
      { label: "Ground Ivy", ids: ["ground-ivy"] },
      { label: "Groundsel", ids: ["groundsel"] },
      { label: "Hawkweed", ids: ["hawkweed"] },
      { label: "Healall", ids: ["healall"] },
      { label: "Henbit", ids: ["henbit"] },
      { label: "Innocence (Blue-eyed Mary)", ids: ["innocence"] },
      { label: "Knotweed", ids: ["knotweed"] },
      { label: "Lambsquarters", ids: ["lambsquarters"] },
      { label: "Lawn Burweed", ids: ["lawn-burweed"] },
      { label: "Lespedeza", ids: ["lespedeza"] },
      { label: "Mallow, Common", ids: ["malva"] },
      { label: "Matchweed", ids: ["matchweed"] },
      { label: "Mouseear Chickweed", ids: ["mouseear-chickweed"] },
      { label: "Nettle", ids: ["stinging-nettle"] },
      { label: "Old World Diamond Flower", ids: ["old-world-diamond-flower"] },
      { label: "Oxalis (Yellow Woodsorrel & Creeping Woodsorrel)", ids: ["woodsorrel-yellow", "woodsorrel-creeping"] },
      { label: "Parsley-Piert", ids: ["parsley-piert"] },
      { label: "Pennsylvania Smartweed", ids: ["smartweed-pennsylvania"] },
      { label: "Pepperweed", ids: ["pepperweed"] },
      { label: "Pigweed", ids: ["pigweed"] },
      { label: "Pineappleweed", ids: ["pineappleweed"] },
      { label: "Plantain", ids: ["plantain"] },
      { label: "Poison Ivy", ids: ["poison-ivy"] },
      { label: "Poison Oak", ids: ["poison-oak-eastern"] },
      { label: "Prickly Lettuce (Compass Plant)", ids: ["prickly-lettuce"] },
      { label: "Puncturevine", ids: ["puncturevine"] },
      { label: "Purple Cudweed", ids: ["cudweed"] },
      { label: "Purslane", ids: ["purslane"] },
      { label: "Ragweed", ids: ["ragweed"] },
      { label: "Red Sorrel (Sheep Sorrel)", ids: ["red-sorrel"] },
      { label: "Shepherd's Purse", ids: ["shepherds-purse"] },
      { label: "Spurge", ids: ["spurge"] },
      { label: "Thistle", ids: ["thistle"] },
      { label: "Virginia Buttonweed", ids: ["virginia-buttonweed"] },
      { label: "White Clover (Dutch Clover, Honeysuckle Clover, White Trefoil & Purplewort)", ids: ["white-clover"] },
      { label: "Wild Carrot", ids: ["wild-carrot"] },
      { label: "Wild Garlic", ids: ["wild-garlic"] },
      { label: "Wild Geranium", ids: ["geranium-wild"] },
      { label: "Wild Lettuce", ids: ["wild-lettuce-tall"] },
      { label: "Wild Mustard", ids: ["mustard-wild"] },
      { label: "Wild Onion", ids: ["wild-onion"] },
      { label: "Wild Strawberry", ids: ["wild-strawberry"] },
      { label: "Wild Violet", ids: ["wild-violet"] },
      { label: "Yarrow", ids: ["yarrow"] },
      { label: "Yellow Rocket", ids: ["yellow-rocket"] },
    ],
    containerSizes: [
      { label: "1 gallon", oz: 128 },
      { label: "2.5 gallon", oz: 320 }
    ], 
    EPAtoxicityLevel: "CAUTION",
    reentryInterval: "Until sprays have dried (agricultural use: 24 hours)",
    applicationNotes: [
        "Apply to actively growing broadleaf weeds — weed control is more effective when daytime air temperatures are above 50°F, soil moisture is adequate, and target weeds are young",
        "Visual symptoms appear within hours of application; plant death typically occurs within 7–14 days",
        "Rainfast in as little as 3 hours; if rain occurs before then, a repeat treatment may be needed",
        "If dry conditions exist, irrigating 24 hours before and 24 hours after application improves weed control",
        "Spring and fall treatments are preferred over summer for older or drought-stressed weeds; fall applications will also control emerged winter annuals such as henbit, chickweed, clover, and ground ivy",
        "A second broadcast application or follow-up spot treatment is advised for mature weeds, dense infestations, or adverse conditions — do not make more than 2 broadcast applications per year",
        "For newly seeded areas: delay application until after the second mowing",
        "For newly sodded, sprigged, or plugged areas: delay application 3–4 weeks after installation",
        "Treated areas may be reseeded 1 week after application",
        "Delay mowing 2 days before and 2 days after application",
        "Do not apply during conditions of low humidity and high temperatures — 2,4-D esters may volatilize under these conditions",
        "Temperatures above 90°F, moist soil, and high humidity increase herbicide activity and the risk of temporary turf discoloration; injury, if it occurs, will resolve after mowing",
        "Do not use adjuvants (surfactants, spreaders, etc.) unless experience confirms they will not cause turf injury — they can damage turfgrass leaf tissue",
        "For Wild Violet: best results when applied in spring while violets are blooming, or as a late-fall application followed by a spring application"
    ],
    restrictions: [
        "For ground application only — aerial applications are not permitted; do not apply through any type of irrigation system",
        "Do not apply to bare ground",
        "Do not allow livestock to graze on treated areas",
        "Do not apply to 'Floratam' or 'Bitterblue' varieties of St. Augustinegrass",
        "Do not apply to bentgrass mowed below ¼ inch",
        "Do not apply to carpetgrass, dichondra, legumes, or lawns where desirable clovers are present",
        "Do not apply to golf course greens",
        "Do not apply to any body of water, shorelines, wetlands, or areas where surface water is present",
        "Do not apply to agricultural irrigation water or irrigation ditch banks or canals",
        "Do not apply when wind speeds exceed 10 mph",
        "Do not alter spray solution pH below 5 or above 8",
        "Max single application: 6 pt/acre (2.2 fl oz/1,000 sq ft)",
        "Max seasonal rate: 12 pt/acre (4.41 fl oz/1,000 sq ft); maximum 2 broadcast applications per year",
        "Minimum interval between applications: 21 days (sod farms); 30 days (non-cropland)",
        "Spot treatments cannot exceed 1,000 sq ft within any given acre"
    ],
    labelUrl: "https://www.cdms.net/ldat/ldH42000.pdf"
  },

  {
  id: "talstar-p-professional",
  fullName: "Talstar P Professional Insecticide",
  brand: "FMC Corporation",
  category: "insecticide",
  type: "residual",
  formulation: "Emulsifiable Concentrate (EC)",
  activeIngredients: ["Bifenthrin 7.9%"],
  genericAlternatives: [
    {
      fullName: "Bifen I/T",
      activeIngredient: "Bifenthrin 7.9%",
      note: "Widely available generic with the same active ingredient and concentration, manufactured by Control Solutions Inc."
    }
  ],
  mixUnit: "fl oz",
  perUnit: "1000 sq ft",
  rateMin: 0.18,
  rateMax: 1.0,
  rateDefault: 0.5,
  annualMaxPer1k: null,
  waterPerUnit: 1,
  turfTypes: [
    "bahiagrass",
    "bermudagrass",
    "bluegrass",
    "buffalograss",
    "centipedegrass",
    "fescue",
    "ryegrass",
    "st-augustinegrass",
    "zoysiagrass"
  ],
  notSafeTurf: [],
  targetWeeds: [],
  containerSizes: [
    { label: "1 gallon", oz: 128 }
  ],
  EPAtoxicityLevel: "III (CAUTION)",
  reentryInterval: "12 hours",
  applicationNotes: [
    "Apply as a broadcast treatment using up to 10 gallons of finished spray per 1,000 sq ft to penetrate thatch, mulch, or dense foliage.",
    "For low-volume applications (less than 2 gal/1,000 sq ft), irrigate immediately after with at least 0.25 inches of water to ensure efficacy against sub-surface pests such as mole crickets.",
    "Lower rate (0.18–0.25 fl oz/1,000 sq ft) targets: Annual Bluegrass Weevil adults, Banks Grass Mite, Billbugs adults, Black Turfgrass Ataenius adults, Centipedes, Crickets, Earwigs, Fleas (adults), Grasshoppers, Leafhoppers, Mealybugs, Millipedes, Mites, Pillbugs, Sowbugs.",
    "Mid rate (0.25–0.5 fl oz/1,000 sq ft) targets: Armyworms, Cutworms, Sod Webworms, Ants, Chinch Bugs, Fleas (larvae), Imported Fire Ants, Japanese Beetle adults, Mole Cricket adults and nymphs, Stink Bugs, Ticks, Crane Flies.",
    "Use 0.5–1.0 fl oz/1,000 sq ft for heavy pest pressure or maximum residual control.",
    "Armyworms, cutworms, sod webworms: delay watering or mowing for 24 hours after application.",
    "Chinch bugs: irrigate before treatment to move the insecticide into the thatch layer where chinch bugs are located.",
    "Mole crickets: apply as late in the day as possible and water in immediately with up to 0.5 inches of water after treatment.",
    "Ticks: treat the entire area — do not spot-treat. Use higher spray volumes in dense ground cover or heavy leaf litter.",
    "Imported Fire Ant mounds: apply 1 fl oz per mound in 1–2 gallons of water; treat 3 feet out around each mound. Break the apex of the mound to allow solution into tunnels. Best applied in cool weather (65–80°F) or early morning/late evening.",
    "Do not apply when wind speed exceeds 10 MPH."
  ],
  restrictions: [
    "Not for use on sod farm turf, golf course turf, or grass grown for seed.",
    "Do not apply by air.",
    "Do not apply through any type of irrigation system.",
    "Do not apply to the point of runoff; do not apply during rain.",
    "Maximum 1.0 fl oz per 1,000 sq ft per application.",
    "At rates below 1.0 fl oz/1,000 sq ft: do not reapply more than once every 7 days.",
    "At 1.0 fl oz/1,000 sq ft: do not reapply more than once every 4 weeks.",
    "New York State only: do not apply to any turf within 100 feet of a lake, pond, river, stream, wetland, or drainage ditch.",
    "Extremely toxic to fish and aquatic invertebrates — prevent runoff or drift to water bodies.",
    "Highly toxic to bees — do not apply when bees are actively foraging or when blooming weeds are present in the treatment area."
  ],
  labelUrl: "https://www.cdms.net/ldat/ld8PP004.pdf"
  },

  {
      id: "tenacity-herbicide",
      fullName: "Tenacity Herbicide, Syngenta",
      brand: "Syngenta",
      category: "herbicide",
      type: ["pre-emergent", "post-emergent"],
      formulation: "liquid",
      activeIngredients: [
          "Mesotrione 40.0%"
      ],
      genericAlternatives: [
        {
            fullName: "Torocity, Atticus",
            activeIngredient: "Mesotrione 40.0%",
            note: "Same active ingredient and concentration. Typically available at lower cost."
        },
        {
            fullName: "Meso 4SC, Prime Source",
            activeIngredient: "Mesotrione 40.0%",
            note: "Same active ingredient and concentration. Typically available at lower cost."
        }
      ],
      mixUnit: "fl oz",
      perUnit: 1000,
      rateMin: 0.092,     // 4 fl oz/acre ÷ 43.56 — general minimum; also St. Augustinegrass sod max
      rateMax: 0.184,     // 8 fl oz/acre ÷ 43.56 — standard turf maximum
      rateDefault: 0.115, // 5 fl oz/acre ÷ 43.56 — most common labeled rate
      turfRates: [
          {
              turfGroup: ["Buffalograss", "Centipedegrass", "Kentucky Bluegrass", "Tall Fescue"],
              rateMin: 0.092,
              rateMax: 0.184
          },
          {
              turfGroup: ["Fine Fescue", "Perennial Ryegrass"],
              rateMin: 0.092,
              rateMax: 0.115, // DO NOT exceed 5 fl oz/acre; applies to mixed stands with >50% perennial ryegrass and/or fine fescue
          },
          {
              turfGroup: ["St. Augustinegrass"],
              rateMin: 0.092,
              rateMax: 0.092, // DO NOT exceed 4 fl oz/acre; sod uses only
              notes: "Sod uses only — DO NOT exceed 4 fl oz/acre"
          }
      ],
      annualMaxPer1k: 0.367,  // 16 fl oz/acre ÷ 43.56
      waterPerUnit: 0.69,     // minimum 30 gal/acre ÷ 43.56; spot treatments use 1 gal/1,000 sq ft
      turfTypes: [
          "Buffalograss",
          "Centipedegrass",
          "Fine Fescue",
          "Kentucky Bluegrass",
          "Perennial Ryegrass",
          "St. Augustinegrass", // sod uses only
          "Tall Fescue"
      ],
      notSafeTurf: [
          "Bermudagrass (sensitive — avoid unless injury can be tolerated; dormant applications only per label)",
          "Creeping Bentgrass (sensitive — avoid unless removal of bentgrass is intended; maintain 5-foot buffer from bentgrass greens)",
          "Kikuyugrass (sensitive — avoid unless control/injury can be tolerated)",
          "Poa annua / Annual Bluegrass (sensitive — maintain 5-foot buffer from Poa annua greens)",
          "Seashore Paspalum (sensitive — avoid unless control/injury can be tolerated)",
          "Zoysiagrass (sensitive — avoid unless control/injury can be tolerated)"
      ],
      targetWeeds: [
        { label: "Barnyardgrass", ids: ["barnyardgrass"] },
        { label: "Bentgrass, Creeping", ids: ["creeping-bentgrass-weed-escape"] },
        { label: "Bluegrass, Annual", ids: ["annual-bluegrass"] },
        { label: "Buckhorn Plantain", ids: ["plantain-buckhorn"] },
        { label: "Buttercup", ids: ["buttercup-sardous"] },
        { label: "Carpetweed", ids: ["carpetweed"] },
        { label: "Chickweed, Common", ids: ["chickweed"] },
        { label: "Chickweed, Mouseear", ids: ["mouseear-chickweed"] },
        { label: "Clover, Large Hop", ids: ["hop-clover-large"] },
        { label: "Clover, White", ids: ["white-clover"] },
        { label: "Crabgrass, Large", ids: ["crabgrass-large"] },
        { label: "Crabgrass, Smooth", ids: ["crabgrass-smooth"] },
        { label: "Crabgrass, Southern", ids: ["crabgrass-hairy"] },
        { label: "Curly Dock", ids: ["dock-curly"] },
        { label: "Dandelion, Catsear", ids: ["catsear"] },
        { label: "Dandelion, Common", ids: ["dandelion"] },
        { label: "Florida Betony", ids: ["florida-betony"] },
        { label: "Florida Pusley", ids: ["florida-pusley"] },
        { label: "Foxtail, Yellow", ids: ["foxtail-yellow"] },
        { label: "Galinsoga", ids: ["galinsoga-hairy"] },
        { label: "Goosegrass", ids: ["goosegrass"] },
        { label: "Ground Ivy", ids: ["ground-ivy"] },
        { label: "Healall", ids: ["healall"] },
        { label: "Henbit", ids: ["henbit"] },
        { label: "Lambsquarters, Common", ids: ["lambsquarters"] },
        { label: "Lawn Burweed", ids: ["lawn-burweed"] },
        { label: "Lovegrass, Tufted", ids: ["lovegrass-tufted"] },
        { label: "Marestail", ids: ["canada-fleabane"] },
        { label: "Nimblewill", ids: ["nimblewill"] },
        { label: "Nutsedge, Yellow", ids: ["nutsedge-yellow"] },
        { label: "Oxalis", ids: ["woodsorrel-yellow"] },
        { label: "Pigweed, Redroot", ids: ["pigweed-redroot"] },
        { label: "Pigweed, Smooth", ids: ["pigweed-smooth"] },
        { label: "Purslane, Common", ids: ["purslane"] },
        { label: "Shepherd's Purse", ids: ["shepherds-purse"] },
        { label: "Smartweed, Pale", ids: ["smartweed-pale"] },
        { label: "Smartweed, Pennsylvania", ids: ["smartweed-pennsylvania"] },
        { label: "Sowthistle", ids: ["common-sowthistle"] },
        { label: "Speedwell, Persian", ids: ["speedwell-persian"] },
        { label: "Speedwell, Purslane", ids: ["speedwell-purslane"] },
        { label: "Swinecress", ids: ["swinecress"] },
        { label: "Thistle, Canada", ids: ["thistle-canada"] },
        { label: "Verbena", ids: ["verbena-blue-vervain"] },
        { label: "Wild Carrot", ids: ["wild-carrot"] },
        { label: "Wild Violet", ids: ["violet-common-blue"] },
        { label: "Windmillgrass", ids: ["windmill-grass-tumble"] }
      ],
      containerSizes: [
        { label: "8 fl oz bottle", oz: 8 },
        { label: "1 gallon", oz: 128 }
      ],
      EPAtoxicityLevel: "CAUTION",
      reentryInterval: "Until sprays have dried (agricultural use: 12 hours)",
      applicationNotes: [
          "Apply preemergence before target weed seed germination; if 0.15 inches of rainfall has not occurred within 10 days of a preemergence application, activate with at least 0.15 inches of irrigation",
          "For postemergence applications, add a non-ionic surfactant (NIS); a repeat application after 2–3 weeks is required for adequate control — weed control is most effective on young, actively growing weeds",
          "Treated weed foliage turns white (loss of chlorophyll) after application; death may take up to three weeks",
          "May cause temporary whitening of turfgrass foliage 5–7 days after application, lasting several weeks; a repeat application to the same site causes less whitening",
          "For preemergence use in established turf, tank mixing with Barricade 65WG (prodiamine) is advised for extended residual and broader weed control coverage",
          "For postemergence removal of creeping bentgrass and nimblewill: apply at 5 fl oz/acre (0.115 fl oz/1,000 sq ft) with NIS at 2–3 week intervals for up to three applications; late summer or early fall timing is more effective than spring or early summer",
          "For best postemergence control of crabgrass and goosegrass, apply when weeds have fewer than 4 tillers",
          "On dormant bermudagrass only: apply at 5 fl oz/acre (0.115 fl oz/1,000 sq ft) to control winter weeds listed on the label; repeat in 2–3 weeks — applications to semi-dormant turf will cause whitening",
          "For new seedings: apply at or close to seeding for best preemergence performance; do not make a postemergence application until newly germinated turf has been mowed twice or 4 weeks after emergence, whichever is longer",
          "Spot application rate: 1 teaspoon of Tenacity per 2 gallons of water, with 3 teaspoons of NIS, applied at 1 gallon per 1,000 sq ft",
          "After application, keep people and pets off treated areas until spray has dried; irrigate lightly to move product off turf foliage before resuming normal irrigation",
          "Avoid overspray or drift onto ornamentals — roses and daylilies are sensitive; avoid applications over exposed roots of trees and ornamentals",
          "Clean sprayer thoroughly after application if the same equipment will be used on bentgrass or bentgrass/Poa annua turf areas"
      ],
      restrictions: [
          "DO NOT apply more than 8 fl oz per acre (0.184 fl oz/1,000 sq ft) in a single application",
          "DO NOT apply more than 16 fl oz per acre (0.367 fl oz/1,000 sq ft) per year — maximum of 2 applications at the full single-application rate",
          "Wait a minimum of 14 days before retreating",
          "DO NOT exceed 5 fl oz per acre (0.115 fl oz/1,000 sq ft) on perennial ryegrass, fine fescues, or mixed stands containing more than 50% perennial ryegrass and/or fine fescue",
          "DO NOT exceed 4 fl oz per acre (0.092 fl oz/1,000 sq ft) on St. Augustinegrass — sod uses only",
          "Tenacity may reduce density of fine fescue seedings; do not use on grass seed blends containing more than 20% by weight of hard or fine fescue",
          "DO NOT use on golf course putting greens; maintain a 5-foot buffer between treated areas and putting greens",
          "Maintain a 5-foot buffer between treated areas and bentgrass or Poa annua greens",
          "DO NOT apply an organophosphate or carbamate insecticide within 7 days of a Tenacity application — turf injury may occur",
          "DO NOT apply through any type of irrigation system",
          "DO NOT apply aerially",
          "DO NOT use grass clippings from treated turf as mulch around trees or in vegetable/flower gardens",
          "DO NOT plant any crop other than turfgrass species for 18 months after the last application",
          "Do not apply when wind speeds exceed 15 mph",
          "Do not apply during temperature inversions",
          "Avoid applications when rainfall or irrigation is expected within 48 hours — product has high potential to reach surface water via runoff"
      ],
      labelUrl: "https://www.cdms.net/ldat/ld8D9005.pdf"
  },

];